(()=>{
const A=window.V5_ASSETS||{};
const BANK=window.V5_BANK||[];
const $=s=>document.querySelector(s);
const app=document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const rng=s=>{let a=hash(s);return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}};
const shuffle=(arr,r=Math.random)=>{arr=[...arr];for(let i=arr.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr};
const strip=s=>String(s||'').replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}]/gu,'').replace(/\s{2,}/g,' ').trim();
const seenKey='behbeh-v5-seen';
const getSeen=()=>{try{return JSON.parse(localStorage.getItem(seenKey)||'[]')}catch{return[]}};
const saveSeen=id=>{const s=getSeen(); if(!s.includes(id)){s.push(id);localStorage.setItem(seenKey,JSON.stringify(s.slice(-500)))}};
const buzz=p=>{try{navigator.vibrate?.(p)}catch{}};

const CURATED=[
{id:'lore-denise',cat:'TAP LORE',type:'choice',prompt:'One person accidentally changed the entire summer by meeting you both in Tap. What did Denise actually set in motion?',options:['She invited you to Kendal Calling','She got Rick an acting audition','She introduced Fats to Rick','She booked the Turkey holiday'],answer:0,reveal:'Denise is the Tap regular-turned-mate who invited you both to Kendal Calling. That is a much bigger plot point than a pub acquaintance has any right to be.'},
{id:'lore-denise-shifts',cat:'TAP LORE',type:'choice',prompt:'If you wanted the highest chance of bumping into Denise behind the bar, which days are the actual canon?',options:['Wednesday and Thursday','Friday and Saturday','Sunday only','Monday and Tuesday'],answer:0,reveal:'Wednesday and Thursday. The game is now legally obliged to treat those as Denise spawning hours.'},
{id:'lore-dad-clock',cat:'TAP LORE',type:'choice',prompt:'Rick’s dad has turned one normal time of day into its own time zone. Which one?',options:['4pm','11am','6pm','8pm'],answer:0,reveal:'Four o’clock. Tap o’clock. A few pints of Swan Blonde and the day has achieved its purpose.'},
{id:'lore-dad-drink',cat:'TAP LORE',type:'choice',prompt:'What is the official fuel of Tap o’clock?',options:['Swan Blonde','Guinness','Tequila','Savvy B'],answer:0,reveal:'Swan Blonde. Not a cocktail. Not a trend. A ritual.'},
{id:'lore-car-glasses',cat:'RICK CORE',type:'choice',prompt:'Before meeting his dad in Tap, which TWO things had Rick managed to lose at the same time?',options:['His car and his glasses','His phone and his coat','His wallet and a shoe','His keys and a pint'],answer:0,reveal:'Car and glasses. Both later recovered. A successful day by the standards of the archive.'},
{id:'lore-fats-freebies',cat:'FATS FILE',type:'choice',prompt:'Fats once appeared bearing a completely random care package. What was in it?',options:['Jeans and skin products','A toaster and socks','Wine and gym gloves','A tent and protein powder'],answer:0,reveal:'Jeans and skin products. Laura was genuinely buzzing. This man operates like an unpredictable subscription box.'},
{id:'lore-fats-location',cat:'FATS FILE',type:'choice',prompt:'Laura once tried to get Fats to share his location for what highly serious reason?',options:['Mostly to see what he would say','To find him in an emergency','To track a lost parcel','To prove he was at work'],answer:0,reveal:'Mostly because it was funny to see what he would say. An extremely responsible use of location services.'},
{id:'lore-train-committee',cat:'TRAVEL CHAOS',type:'choice',prompt:'During the catastrophic train day, Laura somehow created which temporary institution?',options:['A working committee on the train','A passenger choir','A petition against Stafford','A drinks trolley union'],answer:0,reveal:'A working committee. She also made a new friend called Taz while British rail infrastructure disintegrated around them.'},
{id:'lore-stafford',cat:'TRAVEL CHAOS',type:'choice',prompt:'Where did the broken train end up being “fixed” while Laura’s journey unravelled?',options:['Stafford','Crewe','Wigan','Birmingham'],answer:0,reveal:'Stafford. It could take hours, nobody knew anything, and somehow Laura was still networking.'},
{id:'lore-hospital-skin',cat:'LAURA CORE',type:'choice',prompt:'Laura’s brutally affectionate diagnosis of Rick’s complexion in hospital was…',options:['Hospital skin','Ward glow','Morphine chic','Clinical beige'],answer:0,reveal:'Hospital skin. The prescribed treatment was immediately a Korean collagen face mask.'},
{id:'lore-nuffield',cat:'GYM & SAUNA',type:'choice',prompt:'Laura’s original Nuffield pitch had the perfect wellness aftercare. What was it?',options:['Gym, then a drinking session','Gym, then meditation','Gym, then meal prep','Gym, then an early night'],answer:0,reveal:'Gym, then a drinking session. Holistic health.'},
{id:'lore-coffee',cat:'RICK CORE',type:'choice',prompt:'What was the recurring behaviour Laura considered proof Rick was a complete nutcase?',options:['Drinking coffee absurdly late','Cold showers at midnight','Running before breakfast','Eating cereal in pubs'],answer:0,reveal:'Coffee at stupid hours. One night he was literally on the couch drinking it around midnight and she reacted exactly as expected.'},
{id:'lore-greggs',cat:'FOOD LAW',type:'choice',prompt:'Laura’s Greggs order is not “a preference”. It is basically constitutional law. What is it?',options:['Sausage roll','Steak bake','Sausage and bean melt','Chicken bake'],answer:0,reveal:'Sausage roll. Nothing more. Nothing less.'},
{id:'lore-wealthy',cat:'TRAVEL CHAOS',type:'choice',prompt:'What is the agreed aspirational holiday lifestyle?',options:['Wealthy little pigs','Budget goblins','Airport aristocrats','All-inclusive ferals'],answer:0,reveal:'Wealthy little pigs. A surprisingly coherent financial philosophy.'},
{id:'lore-first-water',cat:'ORIGIN STORY',type:'choice',prompt:'Before the first drink even happened, what did Laura briefly think Rick had ordered?',options:['A pint of water','A shandy','A pint of bitter','A glass of wine'],answer:0,reveal:'A pint of water. The relationship nearly began with Rick apparently choosing hydration in a pretentious bar.'},
{id:'lore-m6',cat:'ORIGIN STORY',type:'choice',prompt:'What immediately tried to punish Rick for having a good first meet?',options:['The M6 at a standstill','A parking ticket','A dead phone','A cancelled train'],answer:0,reveal:'The M6. Romance followed immediately by transport infrastructure.'},
{id:'lore-taz',cat:'TRAVEL CHAOS',type:'choice',prompt:'What did Laura somehow gain from the broken-train disaster?',options:['A new friend and proposed double dates','A refund and a hotel','A free first-class upgrade','A job lead'],answer:0,reveal:'A new friend called Taz and an instant double-date plan. This is an aggressively Laura outcome.'},
{id:'lore-music-jehst',cat:'MUSIC RABBIT HOLE',type:'choice',prompt:'Which UK rapper triggered Rick’s “I’m gonna take you down a rabbit hole now” energy?',options:['Jehst','Dave','Skepta','Stormzy'],answer:0,reveal:'Jehst. Dusty, introspective UK hip-hop entered the relationship very early.'},
{id:'lore-playlist',cat:'MUSIC RABBIT HOLE',type:'choice',prompt:'Rick once admitted losing about three hours to what ADHD project?',options:['Building a hip-hop playlist for Laura','Learning a guitar part','Ranking every Outkast track','Making a festival spreadsheet'],answer:0,reveal:'Building Laura a playlist. Three hours disappeared into obscure hip-hop, exactly as nature intended.'},
{id:'lore-kendal-tent',cat:'KENDAL FILES',type:'choice',prompt:'Kendal prep hit crisis mode when which object stopped cooperating?',options:['The tent pole','The camping stove','The car battery','The airbed pump'],answer:0,reveal:'The tent pole. Festival engineering was then solved with the level of confidence normally reserved for bridge construction.'},
{id:'lore-comedy',cat:'PLANS & CHAOS',type:'choice',prompt:'Laura once told Rick to keep which July date free because she was taking him to a comedy gig in Manchester?',options:['18 July','4 July','25 July','31 July'],answer:0,reveal:'18 July. One of many moments where the chat casually turns into an itinerary.'},
{id:'lore-dad-tap',cat:'TAP LORE',type:'choice',prompt:'How did Rick originally describe his dad’s relationship with Tap?',options:['He basically lives in there','He only goes on Fridays','He works there sometimes','He refuses to drink anywhere else'],answer:0,reveal:'“My dad basically lives in there.” The later invention of Tap o’clock merely formalised the arrangement.'},
{id:'lore-music-dc',cat:'MUSIC RABBIT HOLE',type:'choice',prompt:'Which artist had Laura immediately reporting back that the song was another winner for her playlists?',options:['Denzel Curry','Kanye West','Drake','Post Malone'],answer:0,reveal:'Denzel Curry. The music exchange was basically its own early-stage relationship.'},
{id:'lore-watermelon-rare',cat:'DEEP CUT',type:'choice',prompt:'Very occasional deep cut: what bizarre bit of Rick’s dad lore eventually supplied the old safe-word joke?',options:['A boot full of fruit','A pub quiz','A broken lawnmower','A bag of fake watches'],answer:0,reveal:'The boot fruit haul. This joke is now on a strict rationing policy.'}
];

const GENERAL=[
{id:'g1',cat:'WEIRD WORLD',type:'choice',prompt:'A parasite that infects some ants can alter their behaviour before killing them. Which organism is doing the controlling?',options:['A fungus','A flatworm','A bacterium','A moss'],answer:0,reveal:'A fungus in the Ophiocordyceps group. It manipulates the ant’s behaviour before fruiting from the body. Grim, but genuinely fascinating.'},
{id:'g2',cat:'PSYCHOLOGY',type:'choice',prompt:'Which situation is most likely to make a memory feel confident but still be wrong?',options:['Repeatedly retelling it with other people','Writing it down immediately','Seeing a timestamped video','Checking the original message'],answer:0,reveal:'Repeated retelling can make details converge, shift and feel increasingly certain. Confidence is not a perfect lie detector for memory.'},
{id:'g3',cat:'MUSIC',type:'choice',prompt:'Which hip-hop album was the first rap album to win the Grammy for Album of the Year?',options:['Speakerboxxx/The Love Below','The Miseducation of Lauryn Hill','To Pimp a Butterfly','The Marshall Mathers LP'],answer:0,reveal:'Outkast’s Speakerboxxx/The Love Below won Album of the Year in 2004. Lauryn Hill had won earlier, but her record spans hip-hop, R&B and soul rather than being generally classed as a rap album.'},
{id:'g4',cat:'HISTORY',type:'choice',prompt:'Which sounds invented but was a real job in industrial Britain?',options:['Knocker-upper: paid to wake workers by tapping windows','Fog measurer: paid to weigh London fog','Pigeon judge: paid to sentence carrier pigeons','Chimney listener: paid to detect ghosts'],answer:0,reveal:'Knocker-uppers really did wake clients before alarm clocks became common, often using long sticks to tap upstairs windows.'},
{id:'g5',cat:'BODY',type:'choice',prompt:'If you suddenly lose your sense of smell, which everyday ability is usually hit hardest?',options:['Distinguishing flavours','Seeing colour','Feeling temperature','Hearing speech'],answer:0,reveal:'A huge part of what we experience as flavour comes from smell, especially retronasal smell while eating.'},
{id:'g6',cat:'ANIMALS',type:'choice',prompt:'Which animal can deliberately slow its heart rate while diving to conserve oxygen?',options:['A seal','A meerkat','A giraffe','A squirrel'],answer:0,reveal:'Seals and other diving mammals show a powerful dive response, slowing heart rate and prioritising blood flow to vital organs.'},
{id:'g7',cat:'ODD LAW',type:'choice',prompt:'Which strange British legal fact is actually true?',options:['It is illegal to handle salmon in suspicious circumstances','You must bow to every swan on the Thames','Pubs must keep a horse trough outside','It is illegal to whistle after 10pm'],answer:0,reveal:'The Salmon Act 1986 really contains the phrase “handling salmon in suspicious circumstances”. Context makes it less ridiculous, but only slightly.'},
{id:'g8',cat:'MUSIC',type:'choice',prompt:'Which artist released an album made almost entirely around flute rather than rap in 2023?',options:['André 3000','Mos Def','Q-Tip','Tyler, the Creator'],answer:0,reveal:'André 3000 released New Blue Sun, a long-form instrumental record centred on flutes and wind instruments.'},
{id:'g9',cat:'PSYCHOLOGY',type:'choice',prompt:'Why can a song feel faster during exercise even when its BPM has not changed?',options:['Arousal and attention can alter time perception','Your ears physically speed up','Heart rate changes the recording','The brain doubles every fourth beat'],answer:0,reveal:'Arousal, movement and attention can distort subjective time and rhythm perception. The track has not changed; you have.'},
{id:'g10',cat:'WEIRD WORLD',type:'choice',prompt:'Which object has been found to carry a distinct “smell of space” on astronauts’ suits after spacewalks?',options:['Metallic / burnt odours','Fresh grass','Chlorine','Vanilla'],answer:0,reveal:'Astronauts have described metallic, welding-fume or burnt-steak-like smells on equipment after returning to the airlock.'},
{id:'g11',cat:'HISTORY',type:'choice',prompt:'Which disaster sounds like satire but really killed people in London?',options:['A beer flood','A custard avalanche','A gin tornado','A tea explosion'],answer:0,reveal:'The London Beer Flood of 1814 followed the rupture of huge brewery vats. It was real and deadly.'},
{id:'g12',cat:'ANIMALS',type:'choice',prompt:'Which animal group includes species that can sleep with one half of the brain at a time?',options:['Dolphins','Cats','Gorillas','Horses'],answer:0,reveal:'Dolphins can use unihemispheric slow-wave sleep, keeping one half of the brain more alert while the other rests.'}
];

const MINI=['savvy','tapclock','memory','m6','kendal','denise'];
const state={player:localStorage.getItem('behbeh-player')||'Rick',score:0,round:0,seed:'',r:null,sequence:[],mode:'chaos',challenge:false,correct:0,streak:0,best:0,minis:0,bossHits:0};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`};
function pickQuestions(seed,count=6){const r=rng(seed+'-q');const seen=new Set(getSeen());const lore=shuffle(CURATED.filter(q=>!seen.has(q.id)).length>=3?CURATED.filter(q=>!seen.has(q.id)):CURATED,r).slice(0,3);const weird=shuffle(GENERAL.filter(q=>!seen.has(q.id)).length>=2?GENERAL.filter(q=>!seen.has(q.id)):GENERAL,r).slice(0,2);const archiveRaw=BANK.filter(q=>!['who','finish','choice'].includes(q.type)).map(q=>({...q,prompt:strip(q.prompt),reveal:strip(q.reveal),options:(q.options||[]).map(strip)}));const archive=shuffle(archiveRaw.filter(q=>!seen.has(q.id)).length?archiveRaw.filter(q=>!seen.has(q.id)):archiveRaw,r).slice(0,1);return shuffle([...lore,...weird,...archive],r).slice(0,count)}
function buildSequence(seed){const r=rng(seed+'-seq');const qs=pickQuestions(seed,6);const minis=shuffle(MINI,r).slice(0,4);return [
 {kind:'q',data:qs[0]}, {kind:'mini',data:minis[0]}, {kind:'q',data:qs[1]}, {kind:'photo',data:shuffle(['denise','dad','fats'],r)[0]}, {kind:'q',data:qs[2]}, {kind:'mini',data:minis[1]}, {kind:'q',data:qs[3]}, {kind:'mini',data:minis[2]}, {kind:'q',data:qs[4]}, {kind:'boss',data:'fats'}, {kind:'q',data:qs[5]}, {kind:'mini',data:minis[3]}
]}
function setPlayer(p){state.player=p;localStorage.setItem('behbeh-player',p);home()}
function home(){
 const challenge=new URLSearchParams(location.search).get('seed');
 app.innerHTML=`<main class="v5 home"><div class="outsideLogo"><span>RICK & LAURA</span><b>CHAOS QUIZ</b><small>WEIRD QUESTIONS. STUPID GAMES.</small></div><section class="heroV5"><img src="${A.couple_art||''}" class="heroCouple"><div class="heroScribble left">OUR WORLD</div><div class="heroScribble right">NO PATCH NOTES. PROMISE.</div></section>
 <p class="homeLine">A private little gameshow built from the people, places and nonsense that actually make up your life.</p>
 ${challenge?'<div class="challengeNote">A challenge run is waiting. Same sequence. Hidden score.</div>':''}
 <div class="playerPick"><button class="${state.player==='Rick'?'on':''}" data-p="Rick">I'M RICK</button><button class="${state.player==='Laura'?'on':''}" data-p="Laura">I'M LAURA</button></div>
 <div class="homeButtons">
 <button class="launch chaos" data-mode="chaos"><small>MAIN EVENT</small><strong>CHAOS RUN</strong><span>Questions, games, interruptions, characters, one proper boss encounter.</span></button>
 <button class="launch duel" data-mode="challenge"><small>SEND IT</small><strong>CHALLENGE MODE</strong><span>Play first, then send Laura the exact same run without revealing your score.</span></button>
 <button class="launch daily" data-mode="daily"><small>ONE A DAY</small><strong>DAILY EPISODE</strong><span>Same run for both of you today.</span></button>
 <button class="launch quick" data-mode="quick"><small>NO COMMITMENT</small><strong>FIVE-MINUTE BLAST</strong><span>One question, one game, one photo round, one boss phase.</span></button>
 </div>
 <div class="castStrip"><figure><img src="${A.dad||''}"><figcaption>TAP O'CLOCK</figcaption></figure><figure><img src="${A.denise||''}"><figcaption>DENISE</figcaption></figure><figure><img src="${A.fats||''}"><figcaption>FATS</figcaption></figure></div>
 </main>`;
 document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>setPlayer(b.dataset.p));
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));
 if(challenge){document.querySelector('[data-mode="challenge"]').textContent='PLAY THE CHALLENGE';document.querySelector('[data-mode="challenge"]').onclick=()=>start('incoming')}
}
function start(mode){state.mode=mode;state.score=0;state.correct=0;state.streak=0;state.best=0;state.minis=0;state.bossHits=0;state.round=0;const q=new URLSearchParams(location.search);state.seed=mode==='daily'?`daily-${today()}`:mode==='incoming'?(q.get('seed')||`incoming-${Date.now()}`):`v5-${Date.now().toString(36)}`;state.r=rng(state.seed);state.sequence=buildSequence(state.seed);if(mode==='quick')state.sequence=[state.sequence[0],state.sequence[1],state.sequence[3],{kind:'boss',data:'fats'}];render()}
function top(title='CHAOS RUN'){return `<header class="gameTop"><button class="backBtn" id="homeBack">BACK</button><div class="roundDots">${state.sequence.map((x,i)=>`<i class="${i<state.round?'done':i===state.round?'now':''} ${x.kind}"></i>`).join('')}</div><div class="scoreBox">${state.score}</div></header><div class="modeTitle">${title}</div>`}
function render(){const node=state.sequence[state.round];if(!node)return result();if(node.kind==='q')question(node.data);else if(node.kind==='mini')mini(node.data);else if(node.kind==='photo')photoRound(node.data);else if(node.kind==='boss')bossIntro()}
function advance(points=0){state.score+=points;state.round++;render()}
function question(q){saveSeen(q.id);const isTimeline=q.type==='timeline';const opts=q.options||q.events||[];app.innerHTML=`<main class="v5 game">${top(q.cat||q.category||'LORE')}<section class="questionScene"><div class="paperCard"><div class="qType">${isTimeline?'WHICH HAPPENED FIRST?':'CANON CHECK'}</div><h2>${esc(strip(q.prompt))}</h2>${q.date?`<div class="qDate">${esc(q.date)}</div>`:''}</div><div class="answersV5">${opts.map((o,i)=>`<button class="answerV5" data-a="${i}"><b>${String.fromCharCode(65+i)}</b><span>${esc(strip(typeof o==='string'?o:o.text||o.label||''))}</span></button>`).join('')}</div><div id="revealSlot"></div></section></main>`;hookBack();document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>answerQ(q,+b.dataset.a,b))}
function answerQ(q,i,btn){document.querySelectorAll('[data-a]').forEach(b=>b.disabled=true);const ok=i===q.answer;btn.classList.add(ok?'right':'wrong');if(ok){state.correct++;state.streak++;state.best=Math.max(state.best,state.streak);buzz(35)}else{state.streak=0;buzz([40,35,40])}const slot=$('#revealSlot');slot.innerHTML=`<div class="revealV5 ${ok?'good':'bad'}"><strong>${ok?'THAT IS CANON':'ABSOLUTELY NOT'}</strong><p>${esc(strip(q.reveal||''))}</p></div><button id="nextQ" class="nextV5">NEXT</button>`;$('#nextQ').onclick=()=>advance(ok?125+state.streak*15:20)}
function mini(type){state.minis++;if(type==='savvy')return savvy();if(type==='tapclock')return tapclock();if(type==='memory')return memory();if(type==='m6')return m6();if(type==='kendal')return kendal();return deniseGame()}
function microShell(title,sub,body,cls=''){app.innerHTML=`<main class="v5 micro ${cls}">${top('MICROGAME')}<div class="microHeading"><small>DO SOMETHING DIFFERENT</small><h1>${title}</h1><p>${sub}</p></div><section class="microArena">${body}</section></main>`;hookBack()}
function savvy(){let val=18,dir=1,timer=7,hold=false,raf;microShell('SAVE THE SAVVY B','Hold to pour. Release inside Laura’s acceptable zone. Too little is insulting. Too much is a logistics problem.',`<img class="microArt laura" src="${A.laura_art||''}"><div class="wineGlass"><div id="wineFill"></div></div><div class="balanceTrack"><div class="sweet"></div><div id="pourMark"></div></div><button class="holdBtn" id="pour">HOLD TO POUR</button><div class="microClock" id="clock">7.0</div>`,'savvyGame');
const mark=$('#pourMark'),fill=$('#wineFill'),clock=$('#clock');let start=performance.now(),last=start;const tick=now=>{const dt=(now-last)/1000;last=now;if(hold){val+=dt*29*dir;if(val>96){val=96;dir=-1}if(val<4){val=4;dir=1}}mark.style.left=`calc(${val}% - 7px)`;fill.style.height=`${val}%`;timer=7-(now-start)/1000;clock.textContent=Math.max(0,timer).toFixed(1);if(timer<=0)return finish();raf=requestAnimationFrame(tick)};const btn=$('#pour');btn.onpointerdown=e=>{e.preventDefault();hold=true;btn.setPointerCapture?.(e.pointerId)};btn.onpointerup=()=>{hold=false;finish()};const finish=()=>{cancelAnimationFrame(raf);const ok=val>=61&&val<=76;endMicro(ok,ok?'PERFECTLY UNSENSIBLE':'POURING LICENCE REVOKED',ok?'The Savvy B survived with dignity.':'Laura is either parched or carrying a fishbowl.')} ;raf=requestAnimationFrame(tick)}
function tapclock(){let angle=0,speed=2.9,done=false;microShell('TAP O’CLOCK','Stop the hand on exactly four. Your dad is already mentally in the pub.',`<img class="microPhoto dadPhoto" src="${A.dad||''}"><div class="clockV5"><div class="clockNumber n12">12</div><div class="clockNumber n3">3</div><div class="clockNumber n6">6</div><div class="clockNumber n9">9</div><div class="clockHand" id="hand"></div><div class="clockDot"></div></div><button id="stopClock" class="actionV5">STOP THE CLOCK</button>`,'tapGame');
const hand=$('#hand');let last=performance.now();const loop=now=>{if(done)return;angle=(angle+(now-last)*speed/16.67)%360;last=now;hand.style.transform=`translateX(-50%) rotate(${angle}deg)`;requestAnimationFrame(loop)};requestAnimationFrame(loop);$('#stopClock').onclick=()=>{done=true;const target=120;const diff=Math.min(Math.abs(angle-target),360-Math.abs(angle-target));const ok=diff<16;endMicro(ok,ok?'TAP O’CLOCK':'HE IS WAITING',ok?'Close enough. Swan Blonde deployment authorised.':`You stopped at ${clockText(angle)}. Four means four.`)}}
function clockText(a){let mins=Math.round(((a%360)/360)*720);let h=Math.floor(mins/60);let m=mins%60;h=(h||12);return `${h}:${String(m).padStart(2,'0')}`}
function memory(){const items=shuffle(['CAR','GLASSES','KEYS','COAT','PHONE','WALLET'],state.r).slice(0,6);const target='GLASSES';microShell('WHERE ARE THE GLASSES?','You get one second. Then the table gets “Rick’d”. Remember where the glasses were.',`<img class="microArt rick" src="${A.silly_rick||A.rick_art||''}"><div class="memoryGrid">${items.map((x,i)=>`<button class="memoryTile" data-i="${i}"><span>${x}</span></button>`).join('')}</div><div class="memoryCover" id="memoryMsg">MEMORISE</div>`,'memoryGame');const tiles=[...document.querySelectorAll('.memoryTile')];setTimeout(()=>{tiles.forEach(t=>t.classList.add('hiddenLabel'));$('#memoryMsg').textContent='NOW FIND THE GLASSES';tiles.forEach((t,i)=>t.onclick=()=>{const ok=items[i]===target;endMicro(ok,ok?'MIRACLE RECOVERY':'THAT IS NOT THEM',ok?'Car next. One crisis at a time.':'Somewhere, Rick is still squinting.')})},1200)}
function m6(){let lane=1,time=9,alive=true,obs=[],spawn=0,last=performance.now();microShell('ESCAPE THE M6','Survive nine seconds. Left and right only. Lancashire romance depends on it.',`<div class="roadV5" id="road"><div class="laneLine a"></div><div class="laneLine b"></div><div class="m6sign">M6</div><div class="carV5" id="car">R</div></div><div class="driveControls"><button id="left">LEFT</button><button id="right">RIGHT</button></div><div class="microClock" id="clock">9.0</div>`,'m6Game');const road=$('#road'),car=$('#car'),clock=$('#clock');const setLane=()=>car.style.left=`calc(${lane*33.333+16.666}% - 25px)`;setLane();$('#left').onclick=()=>{lane=Math.max(0,lane-1);setLane()};$('#right').onclick=()=>{lane=Math.min(2,lane+1);setLane()};const loop=now=>{if(!alive)return;const dt=(now-last)/1000;last=now;time-=dt;clock.textContent=Math.max(0,time).toFixed(1);spawn-=dt;if(spawn<=0){spawn=.72+state.r()*.45;const l=Math.floor(state.r()*3);const el=document.createElement('div');el.className='trafficV5';el.dataset.l=l;el.style.left=`calc(${l*33.333+16.666}% - 23px)`;el.style.top='-70px';el.textContent=['A','B','C'][l];road.appendChild(el);obs.push({el,y:-70,l})}obs.forEach(o=>{o.y+=dt*195;o.el.style.top=o.y+'px';if(o.y>road.clientHeight-150&&o.y<road.clientHeight-55&&o.l===lane){alive=false;endMicro(false,'STANDSTILL TRAFFIC','The M6 has reclaimed its original role in the relationship.')}});obs=obs.filter(o=>{if(o.y>road.clientHeight+30){o.el.remove();return false}return true});if(time<=0){alive=false;return endMicro(true,'YOU GOT OUT','Against all historical precedent, the M6 allowed passage.')}requestAnimationFrame(loop)};requestAnimationFrame(loop)}
function kendal(){const seq=Array.from({length:4},()=>Math.floor(state.r()*4));let input=[],phase='show';microShell('FIX THE FESTIVAL','Four tent clamps flash in order. Repeat the sequence before the entire Kendal operation folds in on itself.',`<img class="microPhoto deniseSide" src="${A.denise||''}"><div class="tentRig"><div class="tentRoof"></div>${[0,1,2,3].map(i=>`<button class="clamp c${i}" data-c="${i}">${i+1}</button>`).join('')}</div><div class="sequenceNote" id="seqNote">WATCH</div>`,'kendalGame');const btns=[...document.querySelectorAll('[data-c]')];btns.forEach(b=>b.disabled=true);let k=0;const flash=()=>{if(k>=seq.length){phase='play';btns.forEach(b=>b.disabled=false);$('#seqNote').textContent='YOUR TURN';return}const b=btns[seq[k]];b.classList.add('lit');setTimeout(()=>b.classList.remove('lit'),350);k++;setTimeout(flash,560)};setTimeout(flash,500);btns.forEach(b=>b.onclick=()=>{if(phase!=='play')return;const v=+b.dataset.c;input.push(v);b.classList.add('tap');setTimeout(()=>b.classList.remove('tap'),120);const idx=input.length-1;if(v!==seq[idx])return endMicro(false,'TENT COMPROMISED','Denise did not invite you to Kendal for this level of structural engineering.');if(input.length===seq.length)endMicro(true,'FESTIVAL SAVED','Tent remains technically a building. Good enough.')})}
function deniseGame(){let pos=-20,dir=1,done=false;microShell('CATCH DENISE ON SHIFT','Her usual Tap days are Wednesday and Thursday. Stop the moving marker inside either shift window.',`<img class="microPhoto deniseBig" src="${A.denise||''}"><div class="weekTrack"><div class="day">MON</div><div class="day">TUE</div><div class="day hot">WED</div><div class="day hot">THU</div><div class="day">FRI</div><div class="day">SAT</div><div class="day">SUN</div><div class="shiftMarker" id="shift"></div></div><button class="actionV5" id="stopShift">CLOCK HER IN</button>`,'deniseGame');const m=$('#shift');let last=performance.now();const loop=now=>{if(done)return;pos+=((now-last)/1000)*53*dir;last=now;if(pos>98){pos=98;dir=-1}if(pos<0){pos=0;dir=1}m.style.left=pos+'%';requestAnimationFrame(loop)};requestAnimationFrame(loop);$('#stopShift').onclick=()=>{done=true;const day=Math.floor(pos/14.2857);const ok=day===2||day===3;endMicro(ok,ok?'THERE SHE IS':'WRONG DAY',ok?'Kendal-instigator located behind the bar.':'You have arrived at Tap on a Denise-free day.') }}
function endMicro(ok,title,copy){buzz(ok?50:[45,30,45]);const arena=document.querySelector('.microArena');if(!arena)return;arena.insertAdjacentHTML('beforeend',`<div class="microResult ${ok?'good':'bad'}"><strong>${title}</strong><p>${copy}</p><button id="microNext">CONTINUE</button></div>`);$('#microNext').onclick=()=>advance(ok?220:40)}
function photoRound(kind){
 const cards={
  denise:{img:A.denise,title:'ONE WOMAN. ONE VERY LARGE PLOT CONSEQUENCE.',q:'What is Denise’s actual role in the Rick-and-Laura universe?',opts:['Tap mate who invited you both to Kendal Calling','Laura’s old work manager','Rick’s acting teacher','Fats’ sister'],a:0,copy:'Denise is the Tap mate who invited you to Kendal. She also normally appears there on Wednesdays and Thursdays.'},
  dad:{img:A.dad,title:'THE MAN BEHIND TAP O’CLOCK.',q:'What is the actual daily ritual attached to this man?',opts:['Tap at four for a few Swan Blondes','Gym at six then Guinness','Breakfast in Tap every morning','Sunday roast with Fats'],a:0,copy:'Rick’s dad is in Tap at four most days. Tap o’clock, a few pints of Swan Blonde, job done.'},
  fats:{img:A.fats,title:'GORDON, AKA FATS. SOURCE OF CHAOS.',q:'Which completely random gift bundle did Fats actually give Laura?',opts:['Jeans and skin products','A tent and protein powder','A toaster and socks','Wine and gym gloves'],a:0,copy:'Jeans and skin products. It is objectively a strange care package, which makes it perfect Fats lore.'}
 };
 const c=cards[kind]||cards.denise;
 app.innerHTML=`<main class="v5 game photoRound">${top('PHOTO ROUND')}<section class="photoScene"><div class="polaroid"><img src="${c.img||''}"><span>${c.title}</span></div><h2>${c.q}</h2><div class="answersV5">${c.opts.map((o,i)=>`<button class="answerV5" data-pic="${i}"><b>${String.fromCharCode(65+i)}</b><span>${o}</span></button>`).join('')}</div><div id="revealSlot"></div></section></main>`;hookBack();document.querySelectorAll('[data-pic]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-pic]').forEach(x=>x.disabled=true);const ok=+b.dataset.pic===c.a;b.classList.add(ok?'right':'wrong');$('#revealSlot').innerHTML=`<div class="revealV5 ${ok?'good':'bad'}"><strong>${ok?'CORRECT':'NOPE'}</strong><p>${c.copy}</p></div><button id="nextPhoto" class="nextV5">NEXT</button>`;$('#nextPhoto').onclick=()=>advance(ok?150:25)})}
function bossIntro(){app.innerHTML=`<main class="v5 bossIntro"><div class="bossBackdrop"></div><div class="bossLabel">BOSS ENCOUNTER</div><img class="bossFatsPhoto" src="${A.fats||''}"><div class="bossCopy"><small>GORDON HAS ENTERED THE GAME</small><h1>FATS: THREE-PHASE NONSENSE</h1><p>No roast. No fake plate. Actual Fats lore this time.</p><button id="startBoss" class="bossStart">START PHASE ONE</button></div></main>`;$('#startBoss').onclick=()=>bossPhase(1)}
function bossPhase(n){if(n===1)return bossTrain();if(n===2)return bossLocation();if(n===3)return bossFreebies();state.round++;render()}
function bossFrame(n,title,sub,body){app.innerHTML=`<main class="v5 boss"><div class="bossTop"><span>FATS // PHASE ${n} OF 3</span><div class="bossHP"><i style="width:${100-(n-1)*33}%"></i></div></div><h1>${title}</h1><p>${sub}</p><section class="bossArena">${body}</section></main>`}
function bossTrain(){let heat=50,time=8,done=false;bossFrame(1,'TRAIN RAGE','Keep the annoyance needle out of the red while the rail network collapses.',`<img class="bossPortrait" src="${A.fats||''}"><div class="rageMeter"><div class="rageSafe"></div><div id="rageNeedle"></div></div><div class="bossControls"><button id="calm">TELL HIM TO CHILL</button><button id="agree">AGREE THE TRAINS ARE SHIT</button></div><div class="bossClock" id="bossClock">8.0</div>`);const needle=$('#rageNeedle'),clock=$('#bossClock');$('#calm').onclick=()=>heat-=18;$('#agree').onclick=()=>heat+=12;let last=performance.now();const loop=now=>{if(done)return;const dt=(now-last)/1000;last=now;time-=dt;heat+=dt*(7+(state.r()-.5)*8);heat=clamp(heat,0,100);needle.style.left=`calc(${heat}% - 5px)`;clock.textContent=Math.max(0,time).toFixed(1);if(heat>=92){done=true;return bossEnd(false,'FATS HAS LEFT THE GROUP CHAT',()=>bossPhase(2))}if(time<=0){done=true;state.bossHits++;state.score+=250;return bossEnd(true,'RAGE CONTAINED',()=>bossPhase(2))}requestAnimationFrame(loop)};requestAnimationFrame(loop)}
function bossLocation(){let hits=0,time=8,done=false;bossFrame(2,'SHARE YOUR LOCATION','Laura only wanted it because the reply would be funny. Catch three location pings before they disappear.',`<img class="bossPortrait alt" src="${A.fats||''}"><div class="pingField" id="pingField"></div><div class="bossClock" id="bossClock">8.0</div><div class="pingCount" id="pingCount">0 / 3</div>`);const field=$('#pingField'),clock=$('#bossClock'),count=$('#pingCount');function spawn(){if(done)return;field.innerHTML='';const b=document.createElement('button');b.className='ping';b.style.left=(8+state.r()*75)+'%';b.style.top=(8+state.r()*70)+'%';b.textContent='PING';b.onclick=()=>{hits++;count.textContent=`${hits} / 3`;field.innerHTML='';if(hits>=3){done=true;state.bossHits++;state.score+=250;bossEnd(true,'LOCATION ACQUIRED',()=>bossPhase(3))}else spawn()};field.appendChild(b);setTimeout(()=>{if(!done&&field.contains(b))spawn()},950)}spawn();let start=performance.now();const tick=()=>{if(done)return;time=8-(performance.now()-start)/1000;clock.textContent=Math.max(0,time).toFixed(1);if(time<=0){done=true;return bossEnd(false,'PING EXPIRED',()=>bossPhase(3))}requestAnimationFrame(tick)};tick()}
function bossFreebies(){const cards=shuffle([{t:'JEANS',ok:1},{t:'SKIN PRODUCTS',ok:1},{t:'TOASTER',ok:0},{t:'LAMP',ok:0},{t:'FACE MASK',ok:1}],state.r).slice(0,4);let i=0,score=0;bossFrame(3,'THE FREEBIE DROP','Swipe the things Fats actually gave Laura to KEEP. Swipe invented nonsense to BIN.',`<img class="bossPortrait" src="${A.fats||''}"><div class="swipeCard" id="swipeCard"></div><div class="swipeLabels"><span>BIN</span><span>KEEP</span></div>`);const box=$('#swipeCard');function show(){if(i>=cards.length){const ok=score>=3;if(ok){state.bossHits++;state.score+=350}return bossEnd(ok,ok?'BOSS DEFEATED':'FATS REMAINS CONFUSING',()=>{state.round++;render()})}const c=cards[i];box.innerHTML=`<strong>${c.t}</strong><small>SWIPE</small>`;let sx=0,dx=0;box.onpointerdown=e=>{sx=e.clientX;box.setPointerCapture(e.pointerId)};box.onpointermove=e=>{if(!sx)return;dx=e.clientX-sx;box.style.transform=`translateX(${dx}px) rotate(${dx/18}deg)`};box.onpointerup=()=>{const keep=dx>45,bin=dx<-45;if(!keep&&!bin){box.style.transform='';sx=0;dx=0;return}if((keep&&c.ok)||(bin&&!c.ok))score++;i++;sx=0;dx=0;box.style.transform='';show()}}show()}
function bossEnd(ok,title,next){const a=document.querySelector('.bossArena');a.insertAdjacentHTML('beforeend',`<div class="bossResult ${ok?'good':'bad'}"><strong>${title}</strong><button id="bossNext">${state.round===state.sequence.length-1?'FINISH':'NEXT PHASE'}</button></div>`);$('#bossNext').onclick=next}
function result(){const q=new URLSearchParams(location.search);const opp=q.get('score');const from=q.get('from');let title=state.score>1300?'ABSOLUTE MENACE':state.score>900?'VERY SOLID NONSENSE':'CHAOTIC BUT ALIVE';if(opp){title=state.score>+opp?'YOU WON THIS ONE':state.score<+opp?'LAURA/RICK HAS YOU':'DEAD HEAT'}app.innerHTML=`<main class="v5 results"><section class="resultArt"><img src="${A.couple_fest||A.couple_art||''}"><div class="resultTitle">${title}</div></section><section class="resultPanel"><div class="resultScore">${state.score}</div><div class="resultStats"><div><small>CANON HITS</small><b>${state.correct}</b></div><div><small>BEST STREAK</small><b>${state.best}</b></div><div><small>GAMES PLAYED</small><b>${state.minis}</b></div><div><small>FATS DAMAGE</small><b>${state.bossHits}/3</b></div></div>${opp?`<div class="versusLine"><span>${esc(from||'THEM')} ${opp}</span><b>VS</b><span>${state.player} ${state.score}</span></div>`:''}<button class="resultBtn" id="shareRun">${opp?'PLAY ANOTHER':'CHALLENGE THEM'}</button><button class="resultBtn dark" id="backHome">BACK HOME</button></section></main>`;$('#backHome').onclick=()=>{history.replaceState({},'',location.pathname);home()};$('#shareRun').onclick=()=>opp?start('chaos'):shareRun()}
async function shareRun(){const u=new URL(location.href);u.search='';u.searchParams.set('seed',state.seed);u.searchParams.set('score',state.score);u.searchParams.set('from',state.player);const text=`I finished a Behbeh Chaos run. Same run, no peeking at my score.`;try{if(navigator.share)await navigator.share({title:'Rick & Laura Chaos Quiz',text,url:u.toString()});else{await navigator.clipboard.writeText(u.toString());alert('Challenge link copied')}}catch{}}
function hookBack(){const b=$('#homeBack');if(b)b.onclick=home}
home();
})();