window.V7_CURATED = [
{id:'us001',cat:'US',type:'choice',q:'Date one nearly began with the most aggressively sober first impression possible. What did Laura briefly think Rick had ordered?',o:['A pint of water','A lime and soda','A coffee','A non-alcoholic lager'],a:0,r:'Rick wrote “a pint of whatever”. Laura read it as water. “Very classy and dry first impressions” entered the lore immediately.'},
{id:'us002',cat:'US',type:'choice',q:'Laura got to the first bar before Rick and discovered it was basically empty. What nearly happened next?',o:['She headed to The Fleece','She went home','She called Denise','She ordered dinner'],a:0,r:'She considered abandoning ship for The Fleece, then decided she had already ordered and stayed.'},
{id:'us003',cat:'US',type:'choice',q:'What killed the momentum almost immediately after the first meet-up ended?',o:['Standstill traffic on the M6','A flat tyre','A cancelled train','A lost phone'],a:0,r:'Rick hit standstill traffic on the M6. Romance, sponsored by British infrastructure.'},
{id:'us004',cat:'US',type:'choice',q:'Laura said “swear I’m not an alcoholic.” What was Rick’s deeply reassuring response?',o:['It’s fine I am','That makes one of us','I believe you','Same'],a:0,r:'“It’s fine I am.” An elegant tone-setter.'},
{id:'us005',cat:'MUSIC',type:'choice',q:'Which hip-hop legend was accidentally upgraded into “Andrew 3000”?',o:['André 3000','Black Thought','Mos Def','MF DOOM'],a:0,r:'André 3000 became Andrew 3000, then Prince Andrew 3000. It escalated.'},
{id:'us006',cat:'MUSIC',type:'choice',q:'Laura described a Jehst beat with three very specific words. Which set is right?',o:['Dusty, melancholy, introspective','Glossy, euphoric, maximalist','Sparse, tropical, upbeat','Industrial, frantic, metallic'],a:0,r:'Dusty, melancholy and introspective. A remarkably specific compatibility test at one in the morning.'},
{id:'us007',cat:'MUSIC',type:'choice',q:'Rick told Laura he had nearly how many years of hip-hop nerding behind him?',o:['30 years','10 years','15 years','20 years'],a:0,r:'Nearly 30 years. Enough experience to be useful and insufferable in equal measure.'},
{id:'us008',cat:'US',type:'choice',q:'How did Rick identify himself in the very first WhatsApp message?',o:['Rick from the weird friends app','Rick from Tap','The Penwortham hip-hop man','Your impulsive pub stranger'],a:0,r:'“It’s Rick from the weird friends app btw.” Extremely dignified origins.'},
{id:'us009',cat:'TAP + FRIENDS',type:'choice',q:'Before Laura knew Tap, how did Rick locate it for her?',o:['Across the road from Lime Bar','Behind the train station','Next to Greggs','Opposite the library'],a:0,r:'Across the road from Lime Bar. Also: “my dad basically lives in there.”'},
{id:'us010',cat:'TAP + FRIENDS',type:'choice',q:'Rick was trying to meet his dad at Tap but had two small logistical problems. What had he lost?',o:['His car and his glasses','His wallet and coat','His keys and phone','His shoes and dignity'],a:0,r:'He had misplaced both the car and the glasses. The car was later found. So were the glasses.'},
{id:'us011',cat:'TAP + FRIENDS',type:'choice',q:'What completely context-free thing did Rick’s dad once insist he take from the boot of his car?',o:['A huge load of watermelon','A crate of Swan Blonde','A broken gazebo','A box of vinyl'],a:0,r:'Watermelons. No explanation. Just boot fruit.'},
{id:'us012',cat:'US',type:'choice',q:'Why did “watermelon” briefly become a safe word?',o:['Because of Dad’s boot-fruit story','Because Laura hated melon','Because of Kendal Calling','Because Fats ordered one'],a:0,r:'The boot full of melons was so absurd it became the agreed word for “we are getting too ridiculous”.'},
{id:'us013',cat:'TAP + FRIENDS',type:'choice',q:'What time is Tap O’Clock?',o:['4pm','3pm','5pm','Whenever Dad arrives'],a:0,r:'Four o’clock. It is less a time than a constitutional arrangement.'},
{id:'us014',cat:'TAP + FRIENDS',type:'choice',q:'What is Dad’s Tap O’Clock pint?',o:['Swan Blonde','Guinness','Madri','Neck Oil'],a:0,r:'Swan Blonde. The timetable has a beverage specification.'},
{id:'us015',cat:'TAP + FRIENDS',type:'choice',q:'Who turned “people we know from the pub” into “we are apparently going to Kendal Calling”?',o:['Denise','Fats','Dad','Ben'],a:0,r:'Denise. One pub friendship quietly became a festival chapter.'},
{id:'us016',cat:'TRAVEL',type:'choice',q:'The night before Kendal Calling, Rick was “knee deep in tent sorting.” What else was happening?',o:['Slugs were causing a breakdown','The car had vanished','Fats had the tickets','The tent was full of water'],a:0,r:'Slugs. Also a broken tent pole. This was immediately followed by “all is workable.”'},
{id:'us017',cat:'TRAVEL',type:'choice',q:'Which phrase became the official slogan of a broken tent pole and general festival optimism?',o:['All is workable','We move','It’ll buff out','Camping is character building'],a:0,r:'“All is workable.” A phrase with applications far beyond tents.'},
{id:'us018',cat:'US',type:'choice',q:'What economic class did Laura want you two to occupy on holiday?',o:['Wealthy little pigs','Luxury peasants','Budget aristocrats','All-inclusive goblins'],a:0,r:'Wealthy little pigs. Finally, an economic model with emotional clarity.'},
{id:'us019',cat:'US',type:'choice',q:'What unit of time exists only because Laura decided normal minutes were inadequate?',o:['Minnies','Behbeh minutes','Tap seconds','Wade units'],a:0,r:'Minnies. At one point there were 43 of them to go.'},
{id:'us020',cat:'US',type:'choice',q:'Which title did Laura give Rick that he immediately accepted as a promotion?',o:['Silly bullshit bitch','Chaos director','Beautiful goblin','Pub gremlin'],a:0,r:'Silly bullshit bitch. A role with no pension but excellent branding.'},
{id:'us021',cat:'FOOD + DRINK',type:'choice',q:'According to Laura, Greggs is not a choice. It is what?',o:['A summons','A lifestyle','A moral obligation','An emergency service'],a:0,r:'A summons. Specifically in the context of an “illegal sausaj and bean melt”.'},
{id:'us022',cat:'US',type:'choice',q:'What threat did Laura deploy if Rick did not hurry up?',o:['Pee on his car and seriously pursue Adam Driver','Sell his glasses','Tell Dad he hates Swan Blonde','Move to Glasgow'],a:0,r:'The car was threatened and Adam Driver was promoted to active competition.'},
{id:'us023',cat:'US',type:'choice',q:'Rick said he was hunting for his glasses because he was stupid. Laura replied with what?',o:['I love your stupid brain','Use your eyes, four-eyes','Check your face','This is why I drive'],a:0,r:'“I love your stupid brain xxx.” Probably the nicest possible response to losing your glasses again.'},
{id:'us024',cat:'FOOD + DRINK',type:'choice',q:'Rick once announced a plan to eat an entire tub of Ben & Jerry’s and then do what?',o:['Question his capabilities as a functioning adult','Go straight to the gym','Order a Greggs chaser','Sleep for 12 hours'],a:0,r:'Question his capabilities as a functioning adult. Dessert as performance review.'},
{id:'us025',cat:'FATS FILES',type:'choice',q:'In the old-man-pub episode, what unexpected haul did Fats give Laura?',o:['Jeans and skincare','A roast dinner and trainers','A jacket and perfume','Vinyl and sunglasses'],a:0,r:'Jeans and skin products. Laura was buzzing.'},
{id:'us026',cat:'FATS FILES',type:'choice',q:'How did Laura describe the venue while out with Fats and Tom?',o:['An old man pub','A secret club','A hotel bar','A sports bar'],a:0,r:'“Baby we’re in an old man pub.” Immediate field report.'},
{id:'us027',cat:'US',type:'choice',q:'Which imaginary promotion did Laura say had a ring to it?',o:['Detective Sergeant Wade','Professor Wade','DJ Wade','Councillor Wade'],a:0,r:'Detective Sergeant Wade. The investigation department has never recovered.'},
{id:'us028',cat:'MUSIC',type:'choice',q:'When Rick said he was about to take Laura down a music rabbit hole, what was her response?',o:['Take me I love this','Proceed carefully','Not tonight','Only if it is Outkast'],a:0,r:'“Take me I love this.” The exact wrong thing to say to a 30-year hip-hop nerd.'},
{id:'us029',cat:'US',type:'choice',q:'Which of these is NOT one of your established bits of shared vocabulary?',o:['Panic ferret','Minnies','Behbeh','Wealthy little pigs'],a:0,r:'Panic ferret is the imposter. The other three have receipts.'},
{id:'us030',cat:'US',type:'choice',q:'Which sequence actually happened on the first evening?',o:['Pint/water confusion, empty bar, M6 standstill','M6 standstill, empty bar, pint/water confusion','Empty bar, M6 standstill, pint/water confusion','Pint/water confusion, M6 standstill, empty bar'],a:0,r:'Water confusion first, then the empty-bar/Fleece wobble, then the M6 did what the M6 does.'},
{id:'us031',cat:'US',type:'choice',q:'Spot the fake line. Three of these genuinely appeared in your chat.',o:['Behbeh, the moon is tax deductible','All is workable','I love your stupid brain','Greggs isn’t a choice baby, it’s a summons'],a:0,r:'The moon has not yet entered the accounts. The other three are real.'},
{id:'us032',cat:'US',type:'choice',q:'Spot the fake line. Which one did NOT actually happen?',o:['I have audited the vibes and they are unacceptable','Take me I love this','Love going to a pretentious bar for a water','If you don’t hurry up I’m going to pee on your car'],a:0,r:'No formal vibe audit was issued. The other lines are genuine.'},
{id:'us033',cat:'MUSIC',type:'choice',q:'Which progression best captures the Andrew 3000 incident?',o:['André 3000 to Andrew 3000 to Prince Andrew 3000','André 3000 to Andrex 3000 to Prince','Black Thought to Blackpool Thought to Blackpool','Jehst to Jest to Court Jester'],a:0,r:'A simple typo was promoted into a fully fledged royal scandal.'},
{id:'us034',cat:'TRAVEL',type:'choice',q:'Which of these genuinely belonged to pre-Kendal preparation?',o:['A broken tent pole requiring gaffer tape','Buying a canoe','Learning to use a compass','Hiring a generator'],a:0,r:'The pole was broken. The solution was gaffer tape and optimism.'},
{id:'us035',cat:'TAP + FRIENDS',type:'choice',q:'What is the strongest evidence that Dad treats Tap like a second address?',o:['Rick literally said he basically lives there','He owns a key','His post goes there','He has a reserved parking bay'],a:0,r:'The exact description was “my dad basically lives in there.” No tenancy agreement has been found.'},
{id:'us036',cat:'US',type:'choice',q:'What did Laura call the recurring inability to sleep ridiculously late?',o:['The 4am illness','Night goblin syndrome','Behbeh insomnia','The cursed hour'],a:0,r:'The 4am illness. A diagnosis with zero peer review and strong anecdotal evidence.'},
{id:'us037',cat:'FOOD + DRINK',type:'choice',q:'Which drink became the shorthand for medicating the 4am illness?',o:['Savvy B','Espresso martini','Swan Blonde','Tequila soda'],a:0,r:'Savvy B. The medical establishment was not consulted.'},
{id:'us038',cat:'MUSIC',type:'choice',q:'Rick said hip-hop purists miss out if they refuse anything gimmicky. His technical term for that person was?',o:['A wanker','A gatekeeper','A bore','A vinyl goblin'],a:0,r:'“Pure hip hop like a wanker.” Nuanced music criticism.'},
{id:'us039',cat:'US',type:'choice',q:'Which phrase sounds fake but is actually documented?',o:['The coffee mouth is still very much available for use','I have reserved the emotional support sausage roll','The council has banned Behbeh','We need a risk assessment for Tap'],a:0,r:'The coffee mouth was, apparently, still available.'},
{id:'us040',cat:'FATS FILES',type:'choice',q:'Which Fats-related message is real?',o:['Tell Fats I love him','Tell Fats I have his roast','Tell Fats the train is haunted','Tell Fats to bring a watermelon'],a:0,r:'Rick, from hospital, instructed Laura to tell Fats he loved him. A complicated ecosystem.'},

{id:'g001',cat:'ANIMALS',type:'choice',q:'Which animal is famous for producing cube-shaped droppings?',o:['Wombat','Capybara','Badger','Otter'],a:0,r:'Wombats. Their intestines vary in elasticity along their length, helping form the cubes.'},
{id:'g002',cat:'ANIMALS',type:'choice',q:'An octopus has how many hearts?',o:['Three','Two','Four','One'],a:0,r:'Three: two pump blood through the gills and one sends it around the body.'},
{id:'g003',cat:'ANIMALS',type:'choice',q:'Which animal can eject some of its internal organs as a defence and later regrow them?',o:['Sea cucumber','Star-nosed mole','Walrus','Axolotl'],a:0,r:'Sea cucumbers can expel internal organs and regenerate them later.'},
{id:'g004',cat:'ANIMALS',type:'choice',q:'Which frog can survive having much of its body water freeze solid?',o:['Wood frog','Poison dart frog','Bullfrog','Tree frog'],a:0,r:'Wood frogs can survive partial freezing by using cryoprotectants such as glucose.'},
{id:'g005',cat:'ANIMALS',type:'choice',q:'Which animal has pupils that are horizontally rectangular?',o:['Goat','Wolf','Chimpanzee','Seal'],a:0,r:'Goats have horizontal pupils, useful for a wide panoramic view while grazing.'},
{id:'g006',cat:'ANIMALS',type:'choice',q:'Reindeer eyes do something unusual between summer and winter. What?',o:['Change colour from gold to blue','Develop a second pupil','Become ultraviolet-only','Shrink by half'],a:0,r:'Their tapetum lucidum changes from gold in summer to blue in winter, helping in Arctic darkness.'},
{id:'g007',cat:'ANIMALS',type:'choice',q:'Which creature can revert from its adult form back to an earlier life stage, earning the nickname “immortal jellyfish”?',o:['Turritopsis dohrnii','Moon jelly','Portuguese man o’ war','Box jellyfish'],a:0,r:'Turritopsis dohrnii can revert to a juvenile polyp stage under some conditions.'},
{id:'g008',cat:'ANIMALS',type:'choice',q:'A mantis shrimp strike can create what in the water besides the impact itself?',o:['Cavitation bubbles','Tiny whirlpools only','Electric arcs','Ice crystals'],a:0,r:'The strike can create cavitation bubbles whose collapse adds a second shock.'},
{id:'g009',cat:'ANIMALS',type:'choice',q:'What happens to some male deep-sea anglerfish after finding a mate?',o:['They fuse into her body','They build a nest','They change sex','They die immediately'],a:0,r:'In several species, the tiny male permanently fuses to the female and shares her circulation.'},
{id:'g010',cat:'ANIMALS',type:'choice',q:'Which statement is true?',o:['Sharks existed before trees','Trees existed before fish','Sharks evolved after dinosaurs','Whales predate sharks'],a:0,r:'Shark ancestors predate the first trees by tens of millions of years.'},
{id:'g011',cat:'PSYCHOLOGY',type:'choice',q:'Cotard delusion can make someone believe what?',o:['That they are dead or do not exist','That everyone is secretly related','That time is running backwards','That mirrors are portals'],a:0,r:'Cotard delusion can involve believing one is dead, missing organs, or does not exist.'},
{id:'g012',cat:'PSYCHOLOGY',type:'choice',q:'Capgras delusion is the belief that...',o:['Someone close has been replaced by an impostor','You can hear other people’s thoughts','Your body is made of glass','You are living the same day repeatedly'],a:0,r:'Capgras involves believing a familiar person has been replaced by an identical impostor.'},
{id:'g013',cat:'PSYCHOLOGY',type:'choice',q:'What is “jamais vu”?',o:['Something familiar suddenly feels unfamiliar','Seeing faces in objects','Remembering an event that never happened','Thinking you predicted the future'],a:0,r:'Jamais vu is the strange feeling that something familiar is suddenly unfamiliar.'},
{id:'g014',cat:'PSYCHOLOGY',type:'choice',q:'The Zeigarnik effect refers to our tendency to remember...',o:['Unfinished tasks better than finished ones','Embarrassing events in more detail','Faces better than names','Songs heard during adolescence'],a:0,r:'Unfinished or interrupted tasks can remain more mentally accessible than completed ones.'},
{id:'g015',cat:'PSYCHOLOGY',type:'choice',q:'Exploding head syndrome usually involves...',o:['Hearing a sudden imagined bang while falling asleep or waking','A severe migraine with memory loss','A burst blood vessel','Brief total deafness'],a:0,r:'It is a sleep-related phenomenon involving sudden loud imagined noises, usually without pain.'},
{id:'g016',cat:'PSYCHOLOGY',type:'choice',q:'Pareidolia is why you might see...',o:['A face in a plug socket','Colours when hearing music','Your own hand as larger than it is','Motion after staring at a waterfall'],a:0,r:'Pareidolia is finding meaningful patterns, especially faces, in ambiguous stimuli.'},
{id:'g017',cat:'HUMAN BODY',type:'choice',q:'Which part of the human body has no blood vessels and gets oxygen directly from the air?',o:['Cornea','Eardrum','Tongue','Nail bed'],a:0,r:'The cornea is avascular and receives oxygen mainly from the air through the tear film.'},
{id:'g018',cat:'HUMAN BODY',type:'choice',q:'What are the smallest bones in the human body?',o:['The three ossicles in the middle ear','The fingertip bones','The coccyx bones','The nasal bones'],a:0,r:'The malleus, incus and stapes are tiny middle-ear bones; the stapes is the smallest.'},
{id:'g019',cat:'HUMAN BODY',type:'choice',q:'Roughly how many bones are in a typical adult human skeleton?',o:['206','156','256','306'],a:0,r:'The standard count is 206, although small anatomical variations occur.'},
{id:'g020',cat:'HUMAN BODY',type:'choice',q:'What is the body’s largest organ?',o:['Skin','Liver','Lungs','Small intestine'],a:0,r:'Skin is the largest organ by surface area and overall mass.'},
{id:'g021',cat:'HUMAN BODY',type:'choice',q:'Which organ can regrow a substantial amount of lost tissue?',o:['Liver','Spleen','Pancreas','Bladder'],a:0,r:'The liver has a remarkable capacity to regenerate after partial loss.'},
{id:'g022',cat:'HUMAN BODY',type:'choice',q:'Goosebumps are a leftover reflex from when our ancestors...',o:['Had much more body hair','Slept underwater','Changed skin colour seasonally','Used scent glands to communicate'],a:0,r:'Piloerection made thicker body hair stand up, helping trap heat or make an animal look larger.'},
{id:'g023',cat:'HISTORY',type:'choice',q:'In 897, a pope was put on trial despite one major practical issue. What was it?',o:['He was already dead','He was seven years old','He had vanished','He could not speak Latin'],a:0,r:'During the Cadaver Synod, the corpse of Pope Formosus was exhumed and tried.'},
{id:'g024',cat:'HISTORY',type:'choice',q:'What bizarre event hit Strasbourg in 1518?',o:['A dancing plague','A month-long hiccup outbreak','A rain of frogs','A citywide sleepwalking epidemic'],a:0,r:'Hundreds of people reportedly danced compulsively for days or weeks in the 1518 dancing plague.'},
{id:'g025',cat:'HISTORY',type:'choice',q:'Boston’s 1919 disaster involved a deadly flood of what?',o:['Molasses','Beer','Milk','Tar'],a:0,r:'A storage tank burst and a wave of molasses swept through Boston’s North End.'},
{id:'g026',cat:'HISTORY',type:'choice',q:'Mary Toft became infamous in 1726 for claiming she had given birth to...',o:['Rabbits','Fish','A wolf cub','Eggs'],a:0,r:'The English hoax convinced several doctors before being exposed.'},
{id:'g027',cat:'HISTORY',type:'choice',q:'London had a deadly flood in 1814 caused by the bursting of vats containing...',o:['Beer','Gin','Molasses','Vinegar'],a:0,r:'The London Beer Flood killed eight people after a huge porter vat ruptured.'},
{id:'g028',cat:'HISTORY',type:'choice',q:'Which country fought the famously unsuccessful “Emu War” in 1932?',o:['Australia','New Zealand','South Africa','Canada'],a:0,r:'Australian soldiers were deployed against large numbers of emus damaging crops in Western Australia.'},
{id:'g029',cat:'HISTORY',type:'choice',q:'Peter the Great imposed a tax on Russian men who wanted to keep what?',o:['Beards','Moustaches','Long coats','Gold teeth'],a:0,r:'He taxed beards as part of his push to westernise Russian appearance.'},
{id:'g030',cat:'HISTORY',type:'choice',q:'Which institution is older than the Aztec Empire?',o:['Oxford University','The Bank of England','Harvard University','The British Museum'],a:0,r:'Teaching at Oxford dates back to the 11th century; the Aztec Empire was founded in the 15th.'},
{id:'g031',cat:'HISTORY',type:'choice',q:'Cleopatra lived closer in time to which event than to the building of the Great Pyramid?',o:['The Moon landing','The fall of Rome','The Black Death','The invention of printing'],a:0,r:'Cleopatra died in 30 BCE; the Great Pyramid was already over 2,500 years old.'},
{id:'g032',cat:'HISTORY',type:'choice',q:'Nintendo was founded in 1889 to make what?',o:['Playing cards','Mechanical toys','Cameras','Board games'],a:0,r:'Nintendo began as a maker of hanafuda playing cards in Kyoto.'},
{id:'g033',cat:'HISTORY',type:'choice',q:'A working fax-like device was patented before which invention?',o:['The telephone','The steam engine','Photography','The railway'],a:0,r:'Alexander Bain patented an electric printing telegraph in 1843, decades before Bell’s telephone.'},
{id:'g034',cat:'HISTORY',type:'choice',q:'When the pyramids were already ancient, a small population of what animals still survived on Wrangel Island?',o:['Woolly mammoths','Sabre-toothed cats','Giant sloths','Dodos'],a:0,r:'Woolly mammoths survived on Wrangel Island until roughly 2000 BCE.'},
{id:'g035',cat:'MUSIC',type:'choice',q:'What was the first music video played on MTV in 1981?',o:['Video Killed the Radio Star','Take On Me','Money for Nothing','Billie Jean'],a:0,r:'The Buggles’ “Video Killed the Radio Star” opened MTV.'},
{id:'g036',cat:'MUSIC',type:'choice',q:'Queen guitarist Brian May later completed a PhD in...',o:['Astrophysics','Neuroscience','Mechanical engineering','Classical composition'],a:0,r:'May completed a doctorate in astrophysics, decades after pausing it for Queen.'},
{id:'g037',cat:'MUSIC',type:'choice',q:'Which band became the first to perform on all seven continents?',o:['Metallica','U2','Coldplay','Iron Maiden'],a:0,r:'Metallica completed the set by playing Antarctica in 2013.'},
{id:'g038',cat:'MUSIC',type:'choice',q:'The Beatles’ final public performance took place...',o:['On a rooftop','In a train station','On a ferry','Inside Abbey Road studios'],a:0,r:'They performed on the roof of Apple Corps in London in January 1969.'},
{id:'g039',cat:'MUSIC',type:'choice',q:'Who wrote “Nothing Compares 2 U” before Sinéad O’Connor made it globally famous?',o:['Prince','David Bowie','Leonard Cohen','George Michael'],a:0,r:'Prince wrote the song and first released it through his side project The Family.'},
{id:'g040',cat:'MUSIC',type:'choice',q:'David Bowie’s eyes looked like different colours because...',o:['One pupil was permanently dilated after an injury','He wore one coloured contact lens','He had two different iris colours','One eye was prosthetic'],a:0,r:'An injury left one pupil permanently dilated, creating the appearance of different eye colours.'},
{id:'g041',cat:'WEIRD SHIT',type:'choice',q:'Why can fresh pineapple make your mouth feel slightly attacked?',o:['Bromelain enzymes break down proteins','It releases tiny glass-like crystals','Its sugar ferments instantly','Its acid numbs nerves'],a:0,r:'Pineapple contains bromelain, a group of protease enzymes that break down proteins.'},
{id:'g042',cat:'WEIRD SHIT',type:'choice',q:'Botanically speaking, which is a berry?',o:['Banana','Strawberry','Raspberry','Blackberry'],a:0,r:'Bananas qualify as berries botanically; strawberries and raspberries do not.'},
{id:'g043',cat:'WEIRD SHIT',type:'choice',q:'The smell of rain on dry ground has a name. What is it?',o:['Petrichor','Geosmia','Pluviphilia','Ozone bloom'],a:0,r:'Petrichor is the earthy smell associated with rain hitting dry soil.'},
{id:'g044',cat:'WEIRD SHIT',type:'choice',q:'A lightning channel can be roughly how hot compared with the Sun’s surface?',o:['Several times hotter','About half as hot','About the same','Far colder'],a:0,r:'Lightning can briefly heat air to around 30,000 kelvin, several times the Sun’s surface temperature.'},
{id:'g045',cat:'WEIRD SHIT',type:'choice',q:'One day on Venus is...',o:['Longer than one Venus year','Exactly one Earth day','Shorter than one Venus hour','The same length as Mercury’s day'],a:0,r:'Venus rotates so slowly that one sidereal day lasts longer than its year.'},
{id:'g046',cat:'WEIRD SHIT',type:'choice',q:'Do humans emit visible-style light?',o:['Yes, ultraweak light too faint for our eyes','No, never','Only during fever','Only under ultraviolet lamps'],a:0,r:'Human bodies emit ultraweak biophotons, far below the threshold of naked-eye vision.'},
{id:'g047',cat:'WEIRD SHIT',type:'choice',q:'Is old window glass thicker at the bottom because glass slowly flows like a liquid?',o:['No, that is a myth','Yes, over centuries','Only in churches','Only if leaded'],a:0,r:'Old panes were manufactured unevenly and usually installed thick edge down; ordinary glass is not slowly pooling.'},
{id:'g048',cat:'WEIRD SHIT',type:'choice',q:'A typical fluffy cumulus cloud can weigh roughly...',o:['Hundreds of tonnes','Ten kilograms','One tonne at most','Less than the air it displaces'],a:0,r:'Even a modest cloud can contain hundreds of tonnes of water droplets spread through a huge volume.'},
{id:'g049',cat:'WEIRD SHIT',type:'choice',q:'Which statement about honey is closest to true?',o:['Properly sealed honey can remain edible for an extremely long time','Honey always spoils within a year','Honey cannot crystallise','Ancient honey contains no sugar'],a:0,r:'Low moisture and acidity make sealed honey remarkably resistant to spoilage, although it can crystallise.'},
{id:'g050',cat:'WEIRD SHIT',type:'choice',q:'The Eiffel Tower can become slightly taller in summer because...',o:['Metal expands in heat','Wind stretches it','The foundations rise','Tourist weight changes'],a:0,r:'Thermal expansion can change the tower’s height by several centimetres.'}
,{id:'g051',cat:'MUSIC',type:'choice',q:'The title “Smells Like Teen Spirit” came from what?',o:['A deodorant brand reference','A school motto','A punk venue','A discarded lyric'],a:0,r:'Kathleen Hanna wrote “Kurt smells like Teen Spirit”, referring to the deodorant brand. Cobain initially took it as a revolutionary slogan.'}
,{id:'g052',cat:'MUSIC',type:'choice',q:'Who composed the Windows 95 startup sound?',o:['Brian Eno','David Bowie','Trent Reznor','Jean-Michel Jarre'],a:0,r:'Brian Eno composed the short Windows 95 startup sound despite famously not being a Windows user.'}
,{id:'g053',cat:'MUSIC',type:'choice',q:'Which Prince song became a major hit for The Bangles?',o:['Manic Monday','Walk Like an Egyptian','Eternal Flame','Hazy Shade of Winter'],a:0,r:'Prince wrote “Manic Monday” and gave it to The Bangles under a pseudonym.'}
,{id:'g054',cat:'MUSIC',type:'choice',q:'Black Sabbath took their band name from...',o:['A Boris Karloff horror film','A line in Macbeth','An occult book','A Birmingham pub'],a:0,r:'The name came from the 1963 horror film “Black Sabbath”, starring Boris Karloff.'}
,{id:'g055',cat:'PSYCHOLOGY',type:'choice',q:'The Stroop effect is the slowdown you get when...',o:['The meaning of a colour word conflicts with its ink colour','You hear your own recorded voice','You try to remember a face and a name together','You count backwards while walking'],a:0,r:'Naming the ink colour becomes harder when the word itself names a different colour.'}
,{id:'g056',cat:'PSYCHOLOGY',type:'choice',q:'Inattentional blindness means you can...',o:['Miss something obvious while focused on another task','Temporarily lose colour vision','Forget an entire day after stress','See movement that is not there'],a:0,r:'Strong focus can make people fail to notice a very visible unexpected object or event.'}
,{id:'g057',cat:'PSYCHOLOGY',type:'choice',q:'The McGurk effect shows that what you see can change...',o:['What speech sound you think you hear','How sweet food tastes','How quickly time seems to pass','Your sense of balance'],a:0,r:'Visual mouth movements can alter the speech sound the brain reports hearing.'}
,{id:'g058',cat:'PSYCHOLOGY',type:'choice',q:'Phantom vibration syndrome is...',o:['Thinking your phone vibrated when it did not','Feeling an absent limb move','Hearing music inside white noise','Feeling the floor shake after a train'],a:0,r:'Frequent phone users can experience false sensations that a phone vibrated.'}
,{id:'g059',cat:'HUMAN BODY',type:'choice',q:'Mature human red blood cells are unusual because they have no...',o:['Nucleus','Cell membrane','Haemoglobin','Iron'],a:0,r:'Mature red blood cells lose their nucleus, creating more room for haemoglobin.'}
,{id:'g060',cat:'HUMAN BODY',type:'choice',q:'What actually happens to hair and nails after death?',o:['They do not keep growing; skin dries and retracts','They grow for about a week','Only nails keep growing','Only hair keeps growing'],a:0,r:'Dehydration makes surrounding skin retract, creating the illusion of continued growth.'}
,{id:'g061',cat:'HUMAN BODY',type:'choice',q:'The acid in the human stomach is usually around what pH?',o:['About 1 to 3','About 5 to 6','Exactly 7','About 9 to 10'],a:0,r:'Gastric acid is extremely acidic, commonly around pH 1 to 3.'}
,{id:'g062',cat:'HUMAN BODY',type:'choice',q:'Fingerprints begin forming...',o:['Before birth','At puberty','During the first month after birth','Only once babies start gripping things'],a:0,r:'Fingerprint patterns develop in the womb during fetal development.'}
,{id:'g063',cat:'FOOD + DRINK',type:'choice',q:'Why is chocolate dangerous for dogs?',o:['They metabolise theobromine very slowly','They cannot digest cocoa fat','Cocoa blocks vitamin C','Chocolate contains natural alcohol'],a:0,r:'Theobromine can build up to toxic levels in dogs because they process it much more slowly than humans.'}
,{id:'g064',cat:'FOOD + DRINK',type:'choice',q:'The “beans” inside coffee are actually...',o:['Seeds from a fruit','Tiny nuts','Dried roots','Fermented leaves'],a:0,r:'Coffee beans are seeds found inside the fruit commonly called coffee cherries.'}
,{id:'g065',cat:'FOOD + DRINK',type:'choice',q:'Real wasabi is often replaced outside Japan with a mixture based mainly on...',o:['Horseradish','Mustard seed only','Green chilli','Radish leaves'],a:0,r:'Many commercial wasabi pastes use horseradish, mustard and green colouring because true wasabi is expensive and difficult to grow.'}
,{id:'g066',cat:'FOOD + DRINK',type:'choice',q:'Cashew nuts grow...',o:['Outside the bottom of a cashew apple','Underground like peanuts','Inside a hard coconut-like shell','At the centre of a flower'],a:0,r:'The cashew seed hangs beneath the fleshy cashew apple.'}
,{id:'g067',cat:'FOOD + DRINK',type:'choice',q:'Capsaicin makes chilli feel hot because it activates receptors normally involved in sensing...',o:['Heat','Cold','Salt','Pressure'],a:0,r:'Capsaicin activates TRPV1 receptors, which also respond to damaging heat.'}
,{id:'g068',cat:'FOOD + DRINK',type:'choice',q:'Nutmeg can become dangerous in very large amounts because it contains...',o:['Myristicin and other psychoactive compounds','Cyanide in the shell','A natural opioid','Extremely concentrated caffeine'],a:0,r:'Large doses can cause serious poisoning and unpleasant psychoactive effects; it is not a safe recreational drug.'}
,{id:'g069',cat:'FOOD + DRINK',type:'choice',q:'Which common fruit is mildly radioactive because it contains potassium-40?',o:['Banana','Apple','Strawberry','Pineapple'],a:0,r:'Bananas contain naturally occurring potassium-40. The amount is tiny and harmless.'}
,{id:'g070',cat:'TRAVEL',type:'choice',q:'Which country has the most time zones when overseas territories are included?',o:['France','Russia','United States','Australia'],a:0,r:'France spans the most time zones when its overseas territories are counted.'}
,{id:'g071',cat:'TRAVEL',type:'choice',q:'Nepal uses one of the world’s strangest standard time offsets. What is it?',o:['UTC +5:45','UTC +5:20','UTC +6:10','UTC +4:50'],a:0,r:'Nepal Standard Time is UTC +5:45.'}
,{id:'g072',cat:'TRAVEL',type:'choice',q:'What is Salar de Uyuni in Bolivia?',o:['The world’s largest salt flat','The world’s highest lake','A volcanic crater city','A desert made of white sand'],a:0,r:'Salar de Uyuni is the world’s largest salt flat.'}
,{id:'g073',cat:'TRAVEL',type:'choice',q:'Which country has the world’s longest coastline?',o:['Canada','Russia','Indonesia','Australia'],a:0,r:'Canada has by far the longest coastline.'}
,{id:'g074',cat:'TRAVEL',type:'choice',q:'The Atacama is famous for being...',o:['One of the driest non-polar deserts on Earth','The hottest place ever measured','The largest desert on Earth','The only desert beside an ocean'],a:0,r:'Parts of the Atacama are extraordinarily dry, with some weather stations recording almost no rainfall.'}
,{id:'g075',cat:'TRAVEL',type:'choice',q:'Which country is completely surrounded by South Africa?',o:['Lesotho','Eswatini','Botswana','Namibia'],a:0,r:'Lesotho is an enclave entirely surrounded by South Africa.'}
,{id:'g076',cat:'TRAVEL',type:'choice',q:'Why are flights from New York to London often faster than the reverse journey?',o:['The eastbound jet stream often provides a tailwind','Earth rotates under the aircraft','London is at lower altitude','Air is thinner over the Atlantic at night'],a:0,r:'Strong prevailing winds, especially the jet stream, often help eastbound transatlantic flights.'}
,{id:'g077',cat:'TRAVEL',type:'choice',q:'Which inland body of water has shores more than 400 metres below sea level?',o:['The Dead Sea','Lake Baikal','Lake Titicaca','The Caspian Sea'],a:0,r:'The Dead Sea shoreline is the lowest exposed land area on Earth.'}
,{id:'g078',cat:'TRAVEL',type:'choice',q:'Which two sovereign states are completely surrounded by Italy?',o:['Vatican City and San Marino','Monaco and Vatican City','San Marino and Andorra','Liechtenstein and Vatican City'],a:0,r:'Vatican City and San Marino are both enclaves within Italy.'}

];