(()=>{
const A=window.REBORN_ART||{};
const C=window.CHAOS_CONTENT||{questions:[],cameos:[]};
const root=document.getElementById('app');
const $=(tag,cls,html)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(html!==undefined)e.innerHTML=html;return e};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const shuffle=(arr,r=Math.random)=>{const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function rng(seed){let h=2166136261>>>0;for(let i=0;i<seed.length;i++){h^=seed.charCodeAt(i);h=Math.imul(h,16777619)}return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function vibrate(x){try{navigator.vibrate&&navigator.vibrate(x)}catch{}}
const qs=new URLSearchParams(location.search);
const incomingSeed=qs.get('seed');
const incomingMode=qs.get('mode');
const incomingFrom=qs.get('from');
const incomingScore=Number(qs.get('score')||0)||null;
const safeGet=k=>{try{return localStorage.getItem(k)}catch{return null}};const safeSet=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
const state={player:safeGet('chaos_player')||'Rick',score:0,correct:0,streak:0,best:0,index:0,events:[],mode:'home',seed:'',rand:Math.random,started:0,games:0,modifier:null,challenge:false};

function resetPage(){root.innerHTML='';window.scrollTo(0,0);const g=$('div','grain');root.append(g)}
function screen(){const s=$('main','app');root.append(s);return s}
function topbar(title){const wrap=$('div');const t=$('div','topbar');const b=$('button','backBtn','EXIT');b.onclick=()=>renderHome();t.append(b,$('div','topTitle',esc(title)),$('div','topScore',state.score.toLocaleString()));wrap.append(t);const p=$('div','progress');const i=$('i');const total=Math.max(1,state.events.length);i.style.width=(state.index/total*100)+'%';p.append(i);wrap.append(p);return wrap}
function setPlayer(p){state.player=p;safeSet('chaos_player',p);renderHome()}
function todaySeed(){const d=new Date();return `daily-${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function categoryAsset(cat){const map={'MUSIC':'cat_music','TV + FILM':'cat_film','BODY + BRAIN':'cat_body','WEIRD SHIT':'cat_weird','FOOD + DRINK':'cat_food','TRAVEL + FESTIVALS':'cat_travel','OUR WORLD':'cat_us','HISTORY':'cat_history','ANIMALS':'cat_animals'};return A[map[cat]]||A.cat_weird}

function renderHome(){resetPage();state.mode='home';const s=screen();
 const hero=$('section','homeHero');const img=$('img');img.src=A.hero_art;hero.append(img,$('div','heroTape','WEIRD QUESTIONS · STUPID GAMES · OUR WORLD'));s.append(hero);
 if(incomingSeed){const n=$('div','feedback good');n.innerHTML=`<b>${esc(incomingFrom||'Someone')} SENT YOU A RUN</b><p>Same seed. Their score stays hidden until you finish.</p>`;s.append(n)}
 const pr=$('div','playerRow');['Rick','Laura'].forEach(p=>{const b=$('button','playerBtn '+(state.player===p?'on':''),`I'M ${p.toUpperCase()}`);b.onclick=()=>setPlayer(p);pr.append(b)});s.append(pr);
 const stack=$('div','modeStack');
 if(incomingSeed){const b=$('button','modeBtn challenge','<b>PLAY THEIR RUN</b><span>Same questions, same games, no peeking.</span>');b.onclick=()=>launchIncoming();stack.append(b)}else{
  const modes=[
   ['quick','QUICK PLAY','10 rounds. Straight in.','quick'],
   ['episode','EPISODE MODE','Questions, surprises and two games.','episode'],
   ['challenge','CHALLENGE LAURA','Play a seeded round, then send it over.','challenge'],
   ['chaos','CHAOS DECK','Fast games, weird rounds and interruptions.','chaos'],
   ['categories','CATEGORIES','Pick the rabbit hole you actually fancy.','categories']
  ];
  modes.forEach(([id,name,desc,cls])=>{const b=$('button','modeBtn '+cls,`<b>${name}</b><span>${desc}</span>`);b.onclick=()=>launchMode(id);stack.append(b)})
 }
 s.append(stack,$('div','homeFooter','TAP O’CLOCK · MUSIC RABBIT HOLES · M6 RAGE · FESTIVAL DECISIONS · UNEXPECTED VISITORS'));
}
function launchMode(id){if(id==='quick')startQuiz();else if(id==='episode')startEpisode();else if(id==='challenge'){state.challenge=true;startQuiz(null,true)}else if(id==='chaos')startChaos();else renderCategories()}
function launchIncoming(){if(incomingMode==='episode')startEpisode(incomingSeed);else if(incomingMode==='chaos')startChaos(incomingSeed);else startQuiz(null,true,incomingSeed)}

function renderCategories(){resetPage();const s=screen();s.append(topbar('CHOOSE A CATEGORY'));const h=$('div','sectionTitle','<h1>PICK A RABBIT HOLE</h1><p>Music, weirdness, bodies, films, food, travel and your own nonsense.</p>');s.append(h);const grid=$('div','categoryGrid');
 const cats=[['OUR WORLD','cat_us'],['MUSIC','cat_music'],['TV + FILM','cat_film'],['BODY + BRAIN','cat_body'],['WEIRD SHIT','cat_weird'],['FOOD + DRINK','cat_food'],['TRAVEL + FESTIVALS','cat_festival']];
 cats.forEach(([name,key])=>{const b=$('button','cat');const im=$('img');im.src=A[key];b.append(im,$('b','',name));b.onclick=()=>startQuiz(name);grid.append(b)});s.append(grid)
}

function pool(cat){const all=C.questions.filter(q=>!cat||q.cat===cat);return all.length?all:C.questions}
function pickQuestions(cat,count,r){const p=shuffle(pool(cat),r);return p.slice(0,Math.min(count,p.length))}
function resetRun(mode,seed){state.mode=mode;state.seed=seed||`${mode}-${Date.now().toString(36)}`;state.rand=rng(state.seed);state.score=0;state.correct=0;state.streak=0;state.best=0;state.index=0;state.events=[];state.started=Date.now();state.games=0;state.modifier=null}
function startQuiz(cat=null,challenge=false,seed=null){resetRun('quiz'+(cat?':'+cat:''),seed);state.challenge=challenge||!!incomingSeed;let chosen=pickQuestions(cat,14,state.rand);if(!cat)chosen=chosen.filter(q=>q.kind!=='split').slice(0,10);else chosen=chosen.slice(0,10);state.events=chosen.map(q=>({kind:'q',q}));renderEvent()}
function startEpisode(seed=null){resetRun('episode',seed);const q=pickQuestions(null,8,state.rand);const games=shuffle(['beat','savvy','m6','tempo'],state.rand).slice(0,2);state.events=[{kind:'q',q:q[0]},{kind:'q',q:q[1]},{kind:'game',id:games[0]},{kind:'q',q:q[2]},{kind:'cameo'},{kind:'q',q:q[3]},{kind:'q',q:q[4]},{kind:'game',id:games[1]},{kind:'q',q:q[5]},{kind:'q',q:q[6]},{kind:'q',q:q[7]}];renderEvent()}
function startChaos(seed=null){resetRun('chaos',seed);const q=pickQuestions(null,4,state.rand);const games=shuffle(['beat','savvy','m6','tempo'],state.rand);state.events=[{kind:'game',id:games[0]},{kind:'q',q:q[0]},{kind:'cameo'},{kind:'game',id:games[1]},{kind:'q',q:q[1]},{kind:'game',id:games[2]},{kind:'q',q:q[2]},{kind:'cameo'},{kind:'game',id:games[3]},{kind:'q',q:q[3]}];renderEvent()}
function renderEvent(){if(state.index>=state.events.length)return renderResults();const e=state.events[state.index];if(e.kind==='q')renderQuestion(e.q);else if(e.kind==='game')runGame(e.id);else if(e.kind==='cameo')renderCameo()}
function advance(){state.index++;renderEvent()}
function award(ok,base=100){if(ok){state.correct++;state.streak++;state.best=Math.max(state.best,state.streak);let pts=base+state.streak*15;if(state.modifier==='double'){pts*=2;state.modifier=null}state.score+=pts;vibrate(20)}else{if(state.modifier==='shield'){state.modifier=null}else state.streak=0;vibrate([40,25,40])}}

function renderQuestion(q){resetPage();const s=screen();s.append(topbar(q.cat));const w=$('div','qWrap');const stick=$('div','qSticker');const im=$('img');im.src=categoryAsset(q.cat);stick.append(im,$('b','',q.cat));w.append(stick);
 const paper=$('section','paper');let extra='';if(q.kind==='connection')extra=`<div class="clues">${q.clues.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`;paper.innerHTML=`<div class="catname">${esc(labelKind(q.kind))}</div><h1>${esc(q.prompt)}</h1>${extra}`;w.append(paper);s.append(w);
 if(q.kind==='bluff')return renderBool(q,s);if(q.kind==='pick2')return renderPick2(q,s);if(q.kind==='order')return renderOrder(q,s);if(q.kind==='estimate')return renderEstimate(q,s);if(q.kind==='split')return renderSplit(q,s);return renderMCQ(q,s)
}
function labelKind(k){return({mcq:'PICK ONE',scenario:'SCENARIO',bluff:'TRUE OR BULLSHIT',pick2:'PICK TWO',order:'PUT IT IN ORDER',estimate:'HOW CLOSE CAN YOU GET?',split:'NO RIGHT ANSWER',connection:'CONNECTION'}[k]||'QUESTION')}
function feedback(s,ok,q){const f=$('section','feedback '+(ok?'good':'bad'),`<b>${ok?'CORRECT':'NOPE'}</b><p>${esc(q.explain||'')}</p>`);s.append(f);const n=$('button','nextBtn','NEXT');n.onclick=advance;s.append(n);setTimeout(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'}),30)}
function renderMCQ(q,s){const long=(q.options||[]).some(x=>String(x).length>29);const a=$('div','answers'+(long?' single':''));let lock=false;(q.options||[]).forEach((o,i)=>{const b=$('button','answer',`<span class="letter">${String.fromCharCode(65+i)}</span><b>${esc(o)}</b>`);b.onclick=()=>{if(lock)return;lock=true;const ok=i===q.answer;award(ok);[...a.children].forEach((x,j)=>{x.disabled=true;if(j===q.answer)x.classList.add('correct');else if(j===i)x.classList.add('wrong');else x.classList.add('dim')});feedback(s,ok,q)};a.append(b)});s.append(a)}
function renderBool(q,s){const a=$('div','boolAnswers');[['TRUE',true],['BULLSHIT',false]].forEach(([t,v])=>{const b=$('button','answer',t);b.onclick=()=>{const ok=v===q.answer;award(ok);[...a.children].forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');feedback(s,ok,q)};a.append(b)});s.append(a)}
function renderPick2(q,s){s.append($('div','pickHint','Choose two. You can change your mind until you lock it in.'));const long=(q.options||[]).some(x=>String(x).length>29);const a=$('div','answers'+(long?' single':''));const chosen=new Set();(q.options||[]).forEach((o,i)=>{const b=$('button','answer',`<span class="letter">${String.fromCharCode(65+i)}</span><b>${esc(o)}</b>`);b.onclick=()=>{if(chosen.has(i)){chosen.delete(i);b.classList.remove('correct')}else if(chosen.size<2){chosen.add(i);b.classList.add('correct')}check.disabled=chosen.size!==2};a.append(b)});s.append(a);const check=$('button','nextBtn','LOCK IN TWO');check.disabled=true;check.onclick=()=>{const ok=[...chosen].sort().join(',')===[...(q.answers||[])].sort().join(',');award(ok,140);[...a.children].forEach((x,i)=>{x.disabled=true;x.classList.remove('correct');if((q.answers||[]).includes(i))x.classList.add('correct');else if(chosen.has(i))x.classList.add('wrong')});check.remove();feedback(s,ok,q)};s.append(check)}
function renderOrder(q,s){const chosen=[];const list=$('div','orderList');const items=q.items||[];items.forEach((o,i)=>{const b=$('button','orderItem',`<span class="num">–</span>${esc(o)}`);b.onclick=()=>{if(chosen.includes(i))return;chosen.push(i);b.classList.add('chosen');b.querySelector('.num').textContent=chosen.length;if(chosen.length===items.length){const ok=chosen.join(',')===(q.order||[]).join(',');award(ok,160);[...list.children].forEach(x=>x.disabled=true);feedback(s,ok,q)}};list.append(b)});s.append(list)}
function renderEstimate(q,s){const box=$('div','sliderCard');const read=$('div','sliderRead');const r=$('input','range');r.type='range';r.min=q.min;r.max=q.max;r.step=((q.max-q.min)/100)||1;r.value=(q.min+q.max)/2;const update=()=>read.textContent=(Math.round(Number(r.value)*10)/10)+(q.unit||'');update();r.oninput=update;const b=$('button','nextBtn','LOCK IT IN');b.onclick=()=>{const d=Math.abs(Number(r.value)-q.target);const ok=d<=q.tolerance;award(ok,Math.max(60,160-Math.round(d*10)));r.disabled=true;b.remove();const f=$('section','feedback '+(ok?'good':'bad'),`<b>${ok?'CLOSE ENOUGH':'NOT QUITE'}</b><p>${esc(q.explain||'')} Target: ${q.target}${esc(q.unit||'')}.</p>`);s.append(f);const n=$('button','nextBtn','NEXT');n.onclick=advance;s.append(n)};box.append(read,r,b);s.append(box)}
function renderSplit(q,s){const box=$('div','splitAnswers');(q.options||[]).forEach((o,i)=>{const b=$('button','splitAnswer',esc(o));b.onclick=()=>{state.score+=75;vibrate(15);box.innerHTML=`<div class="feedback good"><b>LOCKED IN</b><p>No correct answer. If Laura gets the same run, this is where the argument starts.</p></div>`;const n=$('button','nextBtn','NEXT');n.onclick=advance;s.append(n)};box.append(b)});s.append(box)}

function renderCameo(){resetPage();const s=screen();s.append(topbar('INTERRUPTION'));const pick=C.cameos[Math.floor(state.rand()*C.cameos.length)]||C.cameos[0];const shade=$('div','cameoShade');const card=$('div','cameoCard');const art=$('div','cameoArt');const im=$('img');if(pick.who==='FATS')im.src=A.fats_art;else if(pick.who==='DENISE')im.src=A.cat_festival;else im.src=A.cat_food;art.append(im);const cp=$('div','cameoCopy',`<small>${esc(pick.who)} APPEARS</small><h2>${esc(pick.title)}</h2><p>${esc(pick.body)}</p>`);const choices=$('div','cameoChoice');if(pick.effect==='fats'){[['TAKE THE JEANS',70],['TAKE THE SKINCARE',110]].forEach(([t,pts])=>{const b=$('button','',t);b.onclick=()=>{state.score+=pts;shade.remove();advance()};choices.append(b)})}else{const b=$('button','','CONTINUE');b.onclick=()=>{state.modifier=pick.effect;shade.remove();advance()};choices.append(b)}cp.append(choices);card.append(art,cp);shade.append(card);s.append(shade)}

function gameShell(title,sub){resetPage();const s=screen();s.append(topbar('MINI GAME'));const h=$('div','gameTitle',`<small>MINI GAME</small><h1>${title}</h1><p>${sub}</p>`);const st=$('div','gameStage');s.append(h,st);return {s,st}}
function runGame(id){state.games++;if(id==='beat')return gameBeat();if(id==='savvy')return gameSavvy();if(id==='m6')return gameM6();return gameTempo()}
function gameResult(points,title,body){state.score+=points;resetPage();const s=screen();s.append(topbar('GAME RESULT'));const p=$('section','paper',`<div class="catname">${points} POINTS</div><h1>${esc(title)}</h1><p style="margin:10px 0 0;font-weight:800">${esc(body)}</p>`);s.append(p);const n=$('button','nextBtn','KEEP GOING');n.onclick=advance;s.append(n)}

let audioCtx=null;function tone(freq=220,d=.1,type='sine'){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=.0001;o.connect(g);g.connect(audioCtx.destination);const t=audioCtx.currentTime;g.gain.exponentialRampToValueAtTime(.12,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.start(t);o.stop(t+d+.02)}catch{}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}

async function gameBeat(){const {st}=gameShell('BEAT LAB','Listen, watch, then replay the pad sequence. It gets longer every round.');const bg=$('div','beatBg');bg.style.backgroundImage=`url("${A.beat_art}")`;st.append(bg,$('div','beatVeil'));const dots=$('div','beatDots');st.append(dots);for(let i=0;i<5;i++)dots.append($('i'));const pads=$('div','pads');const freqs=[180,240,320,420];const btns=[];for(let i=0;i<4;i++){const b=$('button','pad');b.setAttribute('aria-label','pad '+(i+1));pads.append(b);btns.push(b)}st.append(pads,$('div','beatStatus','WATCH THE FIRST SEQUENCE'));
 let round=0,score=0,seq=[],input=[],accept=false,dead=false;const status=st.querySelector('.beatStatus');
 const flash=async i=>{btns[i].classList.add('flash');tone(freqs[i],.13,'triangle');await sleep(190);btns[i].classList.remove('flash');await sleep(85)};
 async function show(){accept=false;input=[];status.textContent='WATCH';await sleep(350);for(const i of seq)await flash(i);status.textContent='YOUR TURN';accept=true}
 function fail(){if(dead)return;dead=true;gameResult(Math.max(40,score),'BEAT LOST','You got '+round+' clean round'+(round===1?'':'s')+' before the wheels came off.')}
 async function next(){round++;dots.children[round-1]?.classList.add('on');seq.push(Math.floor(state.rand()*4));if(round>5){dead=true;return gameResult(420,'POCKET LOCKED','Five rounds clean. Preston Nate Dogg would allow it.')}await show()}
 btns.forEach((b,i)=>b.onclick=async()=>{if(!accept||dead)return;await flash(i);input.push(i);const pos=input.length-1;if(input[pos]!==seq[pos])return fail();if(input.length===seq.length){accept=false;score+=65+round*25;status.textContent='CLEAN';await sleep(450);next()}});next()}

function gameSavvy(){const {st}=gameShell('SAVE THE SAVVY B','Drag up to tilt the pour harder. Release when you think the glass is in the green band.');st.classList.add('savvyStage');const bg=$('div','savvyBg');bg.style.backgroundImage=`url("${A.savvy_art}")`;const shade=$('div','savvyShade'),mask=$('div','glassMask'),wine=$('div','dynamicWine'),target=$('div','targetBand'),cover=$('div','emptyCover'),stream=$('div','pourStream'),zone=$('div','tiltZone'),guide=$('div','tiltGuide','DRAG UP TO POUR · RELEASE TO STOP'),read=$('div','fillRead','0%');mask.append(wine,target,cover);st.append(bg,shade,mask,stream,zone,guide,read);
 let fill=0,power=0,drag=false,startY=0,last=performance.now(),done=false,start=last;function setPower(p){power=clamp(p,0,1);bg.style.transform=`scale(1.025) rotate(${(power*3-1.5).toFixed(2)}deg)`;stream.classList.toggle('on',power>.14);stream.style.opacity=power>.14?String(.3+.7*power):'0'}
 zone.onpointerdown=e=>{drag=true;startY=e.clientY;zone.setPointerCapture?.(e.pointerId);guide.textContent='MORE TILT = FASTER POUR'};zone.onpointermove=e=>{if(!drag)return;setPower((startY-e.clientY+25)/180)};const release=()=>{if(!drag||done)return;drag=false;setPower(0);finish()};zone.onpointerup=zone.onpointercancel=release;
 function finish(){if(done)return;done=true;const d=Math.abs(fill-.73);const over=fill>.94;const pts=over?35:Math.max(60,360-Math.round(d*700));st.classList.toggle('spill',over);setTimeout(()=>gameResult(pts,over?'TABLE WINE':'POUR COMPLETE',over?'You have technically served the furniture.':d<.035?'That is offensively accurate.':d<.1?'Perfectly respectable.':'At least the glass was involved.'),420)}
 function tick(t){if(done)return;const dt=Math.min(.04,(t-last)/1000);last=t;if(power>.01)fill+=dt*(.035+.22*power);fill=clamp(fill,0,1.04);wine.style.height=(Math.min(fill,1)*100)+'%';cover.style.height=((1-Math.min(fill,1))*100)+'%';read.textContent=Math.round(fill*100)+'%';st.classList.toggle('goodZone',fill>.66&&fill<.8);if(fill>=1.03||t-start>10000)return finish();requestAnimationFrame(tick)}requestAnimationFrame(tick)}

function gameM6(){const {st}=gameShell('M6 MADNESS','Swipe or tap lanes. Survive the traffic wave without collecting anyone’s bumper.');st.classList.add('roadStage');const art=$('div','roadArt');art.style.backgroundImage=`url("${A.m6_art}")`;const cv=$('canvas','roadCanvas');st.append(art,cv);const ctr=$('div','laneButtons');const left=$('button','','LEFT'),right=$('button','','RIGHT');ctr.append(left,right);st.append(ctr);const read=$('div','m6Read','0.0s');st.append(read);
 const ctx=cv.getContext('2d');let lane=1,obs=[],done=false,start=performance.now(),last=start,spawn=0,score=0;function resize(){const r=st.getBoundingClientRect();cv.width=r.width*devicePixelRatio;cv.height=r.height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();addEventListener('resize',resize,{once:true});
 const setLane=d=>{lane=clamp(lane+d,0,2);vibrate(8)};left.onclick=()=>setLane(-1);right.onclick=()=>setLane(1);let sx=null;st.onpointerdown=e=>sx=e.clientX;st.onpointerup=e=>{if(sx==null)return;const dx=e.clientX-sx;if(Math.abs(dx)>35)setLane(dx<0?-1:1);sx=null};
 function car(x,y,w,h,color,player=false){ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.roundRect(-w/2+3,-h/2+7,w,h,10);ctx.fill();ctx.fillStyle='#05070a';ctx.fillRect(-w/2-4,-h*.28,7,h*.24);ctx.fillRect(w/2-3,-h*.28,7,h*.24);ctx.fillRect(-w/2-4,h*.12,7,h*.24);ctx.fillRect(w/2-3,h*.12,7,h*.24);ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,10);ctx.fill();ctx.fillStyle='rgba(255,255,255,.16)';ctx.beginPath();ctx.roundRect(-w*.34,-h*.38,w*.68,h*.23,7);ctx.fill();ctx.fillStyle='#b9e8ff';ctx.beginPath();ctx.roundRect(-w*.28,-h*.18,w*.56,h*.25,6);ctx.fill();ctx.fillStyle=player?'#cbff38':'#ffefb0';ctx.fillRect(-w*.29,h*.27,9,6);ctx.fillRect(w*.20,h*.27,9,6);ctx.fillStyle='#ff4b5d';ctx.fillRect(-w*.29,-h*.42,9,5);ctx.fillRect(w*.20,-h*.42,9,5);ctx.restore()}
 function finish(){if(done)return;done=true;gameResult(Math.round(120+score*18),'M6 SURVIVED','You lasted '+score.toFixed(1)+' seconds without becoming an insurance claim.')}
 function tick(t){if(done)return;const dt=Math.min(.04,(t-last)/1000);last=t;const r=st.getBoundingClientRect(),w=r.width,h=r.height;ctx.clearRect(0,0,w,h);const roadL=w*.11,roadR=w*.89,laneW=(roadR-roadL)/3;ctx.fillStyle='rgba(9,12,16,.72)';ctx.fillRect(roadL,0,roadR-roadL,h);ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=3;ctx.setLineDash([28,28]);for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(roadL+laneW*i,0);ctx.lineTo(roadL+laneW*i,h);ctx.stroke()}ctx.setLineDash([]);spawn-=dt;if(spawn<=0){spawn=Math.max(.42,.9-score*.025);const l=Math.floor(state.rand()*3);obs.push({lane:l,y:-70,speed:185+state.rand()*95});if(score>5&&state.rand()<.28){let l2=(l+1+Math.floor(state.rand()*2))%3;obs.push({lane:l2,y:-140,speed:205+state.rand()*70})}}
 const px=roadL+laneW*(lane+.5),py=h-118;for(const o of obs){o.y+=o.speed*dt;const ox=roadL+laneW*(o.lane+.5);car(ox,o.y,48,76,'#ff5368');if(Math.abs(o.y-py)<65&&o.lane===lane){done=true;vibrate([70,30,70]);return gameResult(Math.round(60+score*10),'BUMPER ACQUIRED','The M6 has once again defeated human optimism.')}}obs=obs.filter(o=>o.y<h+100);car(px,py,52,82,'#29bfff',true);score=(t-start)/1000;read.textContent=score.toFixed(1)+'s';if(score>=14)return finish();requestAnimationFrame(tick)}requestAnimationFrame(tick)}

async function gameTempo(){const {st}=gameShell('TEMPO LOCK','Four clicks, then silence. Keep the pulse going for six taps without the metronome helping.');st.classList.add('tempoStage');const status=$('div','tempoStatus','LISTEN');const disc=$('div','tempoDisc'),pulse=$('div','tempoPulse');disc.append(pulse);const tap=$('button','tempoTap','TAP');st.append(status,disc,tap);const bpm=92+Math.floor(state.rand()*28),interval=60000/bpm;let targets=[],taps=[],accept=false,startT=0;
 for(let i=0;i<4;i++){pulse.classList.remove('go');void pulse.offsetWidth;pulse.classList.add('go');tone(500,.08,'square');status.textContent=`${bpm} BPM · LISTEN`;await sleep(interval)}status.textContent='NOW HOLD IT IN YOUR HEAD';await sleep(interval);startT=performance.now();for(let i=0;i<6;i++)targets.push(startT+i*interval);accept=true;
 tap.onclick=()=>{if(!accept)return;const t=performance.now();tone(180,.05,'triangle');taps.push(t);pulse.classList.remove('go');void pulse.offsetWidth;pulse.classList.add('go');if(taps.length===6){accept=false;const errs=taps.map((x,i)=>Math.abs(x-targets[i]));const avg=errs.reduce((a,b)=>a+b,0)/errs.length;const pts=Math.max(40,360-Math.round(avg*2.2));gameResult(pts,avg<45?'POCKET FOUND':avg<90?'MOSTLY THERE':'TEMPO DRIFT',`Average timing error: ${Math.round(avg)} ms.`)}}}

function renderResults(){resetPage();const s=screen();const top=$('section','resultTop');const im=$('img');im.src=A.result_art;const shade=$('div','resultShade');const copy=$('div','resultCopy',`<h1>${state.mode==='chaos'?'CHAOS SURVIVED':'ROUND COMPLETE'}</h1><div class="score">${state.score.toLocaleString()}</div>`);top.append(im,shade,copy);s.append(top);const st=$('div','stats');const qTotal=state.events.filter(e=>e.kind==='q').length;[['QUESTIONS',`${state.correct}/${qTotal}`],['GAMES',state.games],['BEST STREAK',state.best]].forEach(([a,b])=>st.append($('div','stat',`<small>${a}</small><b>${b}</b>`)));s.append(st);if(incomingScore){const cmp=state.score-incomingScore;const f=$('div','feedback '+(cmp>=0?'good':'bad'),`<b>${cmp>=0?'YOU BEAT THEM':'THEY GOT YOU'}</b><p>${incomingScore.toLocaleString()} vs ${state.score.toLocaleString()}.</p>`);s.append(f)}const actions=$('div','resultActions');const again=$('button','again','PLAY AGAIN');again.onclick=()=>{if(state.mode==='episode')startEpisode();else if(state.mode==='chaos')startChaos();else startQuiz(state.mode.includes(':')?state.mode.split(':')[1]:null)};actions.append(again);const share=$('button','share','CHALLENGE LAURA');share.onclick=shareRun;actions.append(share);const home=$('button','homeBack','BACK TO MENU');home.onclick=renderHome;actions.append(home);s.append(actions)}
async function shareRun(){const u=new URL(location.href);u.search='';u.searchParams.set('seed',state.seed);u.searchParams.set('mode',state.mode);u.searchParams.set('from',state.player);u.searchParams.set('score',state.score);const txt=`I scored ${state.score.toLocaleString()} on Rick + Laura Chaos Quiz. Same run. Your turn.`;try{if(navigator.share)await navigator.share({title:'Rick + Laura Chaos Quiz',text:txt,url:u.toString()});else{await navigator.clipboard.writeText(txt+' '+u);alert('Challenge link copied')}}catch{}}

renderHome();
})();